"""HTTP routes for the Anva API and server-rendered application."""

from __future__ import annotations

from django.urls import path

from anva.core import views as core_views
from anva.foundation import views

urlpatterns = [
    path("", views.home, name="home"),
    path("health/live", views.liveness, name="liveness"),
    path("health/ready", views.readiness, name="readiness"),
    path("api/v1/bootstrap", core_views.bootstrap, name="api-v1-bootstrap"),
    path(
        "api/v1/organizations/<uuid:organization_id>",
        core_views.organization_detail,
        name="api-v1-organization",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/members",
        core_views.memberships,
        name="api-v1-memberships",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/members/<uuid:membership_id>",
        core_views.membership_detail,
        name="api-v1-membership",
    ),
    path(
        "api/v1/repositories/<uuid:repository_id>/tokens",
        core_views.repository_tokens,
        name="api-v1-repository-tokens",
    ),
    path(
        "api/v1/tokens/<uuid:token_id>/rotate",
        core_views.rotate_token,
        name="api-v1-token-rotate",
    ),
    path(
        "api/v1/tokens/<uuid:token_id>",
        core_views.revoke_token,
        name="api-v1-token-revoke",
    ),
    path("api/v1/search", core_views.search, name="api-v1-search"),
    path("api/v1/query", core_views.query, name="api-v1-query"),
    path(
        "api/v1/context-packets",
        core_views.context_packets,
        name="api-v1-context-packets",
    ),
    path(
        "api/v1/context-packets/<uuid:packet_id>",
        core_views.context_packet_detail,
        name="api-v1-context-packet",
    ),
    path(
        "api/v1/entities/<uuid:entity_id>/relationships",
        core_views.entity_relationships,
        name="api-v1-entity-relationships",
    ),
    path(
        "api/v1/entities/<uuid:entity_id>/history",
        core_views.entity_history,
        name="api-v1-entity-history",
    ),
    path(
        "api/v1/entities/<uuid:entity_id>/sources",
        core_views.entity_sources,
        name="api-v1-entity-sources",
    ),
    path(
        "api/v1/assertions/<uuid:assertion_id>/explanation",
        core_views.assertion_explanation,
        name="api-v1-assertion-explanation",
    ),
    path(
        "api/v1/canvas/assertions/<uuid:assertion_id>",
        core_views.canvas_assertion,
        name="api-v1-canvas-assertion",
    ),
    path("api/v1/mcp/context", core_views.mcp_context, name="api-v1-mcp-context"),
    path(
        "api/v1/artifacts/<uuid:artifact_id>",
        core_views.artifact_detail,
        name="api-v1-artifact",
    ),
    path(
        "api/v1/work-items",
        core_views.work_items_import,
        name="api-v1-work-items-create",
    ),
    path(
        "api/v1/work-items/import",
        core_views.work_items_import,
        name="api-v1-work-items-import",
    ),
    path(
        "api/v1/work-items/<uuid:work_item_id>",
        core_views.work_item_detail,
        name="api-v1-work-item",
    ),
    path(
        "api/v1/work-item-revisions/<uuid:work_item_revision_id>/approvals",
        core_views.work_revision_approval,
        name="api-v1-work-revision-approval",
    ),
    path(
        "api/v1/work-approvals/<uuid:approval_id>/revoke",
        core_views.work_approval_revocation,
        name="api-v1-work-approval-revoke",
    ),
    path(
        "api/v1/work-item-revisions/<uuid:work_item_revision_id>/evidence-map",
        core_views.criterion_evidence_mapping,
        name="api-v1-work-revision-evidence-map",
    ),
    path(
        "api/v1/policies",
        core_views.policies_import,
        name="api-v1-policies-create",
    ),
    path(
        "api/v1/policies/import",
        core_views.policies_import,
        name="api-v1-policies-import",
    ),
    path(
        "api/v1/policies/simulate",
        core_views.policy_simulation,
        name="api-v1-policies-simulate",
    ),
    path(
        "api/v1/policies/<uuid:policy_id>",
        core_views.policy_detail,
        name="api-v1-policy",
    ),
    path(
        "api/v1/repositories/<uuid:repository_id>/pull-requests/<int:pull_request_number>/evidence",
        core_views.evidence_submission,
        name="api-v1-evidence-submit",
    ),
    path(
        "api/v1/evidence-manifests/<uuid:manifest_id>",
        core_views.evidence_manifest_detail,
        name="api-v1-evidence-manifest",
    ),
    path(
        "api/v1/policy-overrides/<uuid:policy_override_id>/revoke",
        core_views.policy_override_revocation,
        name="api-v1-policy-override-revoke",
    ),
    path(
        "api/v1/knowledge/assertions/<uuid:assertion_id>/review",
        core_views.review_knowledge,
        name="api-v1-knowledge-review",
    ),
    path(
        "api/v1/assurance-runs/<uuid:run_id>/transition",
        core_views.transition_assurance,
        name="api-v1-assurance-transition",
    ),
    path(
        "api/v1/findings/<uuid:finding_id>/dismiss",
        core_views.dismiss_finding,
        name="api-v1-finding-dismiss",
    ),
    path(
        "api/v1/policies/<uuid:policy_id>/override",
        core_views.override_policy,
        name="api-v1-policy-override",
    ),
    path(
        "api/v1/source-connections/<uuid:source_connection_id>/revoke",
        core_views.revoke_source,
        name="api-v1-source-revoke",
    ),
    path(
        "api/v1/source-connections/filesystem",
        core_views.connect_filesystem,
        name="api-v1-source-connect-filesystem",
    ),
    path(
        "api/v1/source-connections/<uuid:source_connection_id>",
        core_views.source_detail,
        name="api-v1-source-detail",
    ),
    path(
        "api/v1/source-connections/<uuid:source_connection_id>/sync",
        core_views.sync_source,
        name="api-v1-source-sync",
    ),
    path(
        "api/v1/source-connections/<uuid:source_connection_id>/resync",
        core_views.resync_source,
        name="api-v1-source-resync",
    ),
    path(
        "api/v1/source-connections/<uuid:source_connection_id>/sync-runs",
        core_views.source_runs,
        name="api-v1-source-runs",
    ),
]
