# Generated by Django 5.2.5 on 2026-07-28 00:00
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImmutableArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONTEXT_PACKET", "Context Packet"),
                            ("EVIDENCE_MANIFEST", "Evidence Manifest"),
                            ("ASSURANCE_REPORT", "Assurance Report"),
                            ("RENDERED_EXTERNAL_CONTENT", "Rendered External Content"),
                        ],
                        max_length=32,
                    ),
                ),
                ("schema_name", models.CharField(max_length=100)),
                ("schema_version", models.CharField(max_length=20)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("lease_owner", models.CharField(blank=True, max_length=200, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=200)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_type", models.CharField(max_length=50)),
                ("actor_id", models.CharField(max_length=200)),
                ("action", models.CharField(max_length=200)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.UUIDField()),
                ("from_state", models.CharField(max_length=50)),
                ("to_state", models.CharField(max_length=50)),
                ("authorization_path", models.CharField(max_length=500)),
                ("request_id", models.UUIDField()),
                ("source_ip_hash", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssuranceRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("repository_external_id", models.CharField(max_length=300)),
                ("pull_request_number", models.PositiveIntegerField()),
                ("head_commit", models.CharField(max_length=64)),
                ("evaluated_commit", models.CharField(blank=True, max_length=64)),
                ("report_commit", models.CharField(blank=True, max_length=64)),
                ("policy_version", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("DEBOUNCING", "Debouncing"),
                            ("FETCHING_PULL_REQUEST", "Fetching Pull Request"),
                            ("COLLECTING_EVIDENCE", "Collecting Evidence"),
                            ("EVALUATING_POLICY", "Evaluating Policy"),
                            ("BUILDING_CONTEXT", "Building Context"),
                            ("MODEL_REVIEW", "Model Review"),
                            ("MAPPING_EVIDENCE", "Mapping Evidence"),
                            ("RENDERING_REPORT", "Rendering Report"),
                            ("PUBLISHING", "Publishing"),
                            ("COMPLETED", "Completed"),
                            ("STALE", "Stale"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "context_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.immutableartifact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=200)),
                ("payload", models.JSONField()),
                ("idempotency_key", models.CharField(max_length=300)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("external_key", models.CharField(max_length=300)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("AUTHORIZING", "Authorizing"),
                            ("ACTIVE", "Active"),
                            ("DEGRADED", "Degraded"),
                            ("REVOKED", "Revoked"),
                            ("DISABLED", "Disabled"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("DISCOVERING", "Discovering"),
                            ("FETCHING", "Fetching"),
                            ("PARSING", "Parsing"),
                            ("INDEXING", "Indexing"),
                            ("EXTRACTING", "Extracting"),
                            ("RESOLVING", "Resolving"),
                            ("PUBLISHING", "Publishing"),
                            ("COMPLETED", "Completed"),
                            ("PARTIALLY_COMPLETED", "Partially Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=24,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourceconnection"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("summary", models.TextField()),
                ("proposed_changes", models.JSONField()),
                ("anva_sources", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("VALIDATING", "Validating"),
                            ("AWAITING_REVIEW", "Awaiting Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="core_knowledgeproposal_revision_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("anva_sources", []), _negated=True),
                        name="core_proposal_sources_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("proposed_changes", []), _negated=True),
                        name="core_proposal_changes_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("decided_at__isnull", False),
                                (
                                    "state__in",
                                    ["ACCEPTED", "REJECTED", "SUPERSEDED", "FAILED"],
                                ),
                            ),
                            models.Q(
                                ("decided_at__isnull", True),
                                ("state__in", ["PROPOSED", "VALIDATING", "AWAITING_REVIEW"]),
                            ),
                            _connector="OR",
                        ),
                        name="core_proposal_decision_time_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeAssertion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("subject_key", models.CharField(max_length=500)),
                ("predicate", models.CharField(max_length=200)),
                ("value", models.JSONField()),
                ("is_inferred", models.BooleanField(default=False)),
                ("provenance", models.JSONField(default=list)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("UNREVIEWED", "Unreviewed"),
                            ("AUTO_ACCEPTED", "Auto Accepted"),
                            ("HUMAN_CONFIRMED", "Human Confirmed"),
                            ("DISPUTED", "Disputed"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                            ("STALE", "Stale"),
                        ],
                        default="UNREVIEWED",
                        max_length=24,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "subject_key", "predicate"],
                        name="core_assert_subject_pred_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="core_knowledgeassertion_revision_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provenance", []), _negated=True),
                        name="core_assertion_provenance_not_empty",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="immutableartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_artifact_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="immutableartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_artifact_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="immutableartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind", "content_hash"),
                name="core_artifact_org_kind_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="immutableartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_artifact_org_id_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["state", "available_at", "-priority", "created_at"],
                name="core_job_claim_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="core_job_org_idempotency_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)), name="core_job_max_attempts_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="core_job_attempt_within_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_owner__isnull", False),
                        ("state", "RUNNING"),
                    ),
                    models.Q(
                        models.Q(("state", "RUNNING"), _negated=True),
                        ("lease_owner__isnull", True),
                        ("lease_expires_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="core_job_lease_state_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization", "target_type", "target_id", "created_at"],
                name="core_audit_target_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "request_id",
                    "target_type",
                    "target_id",
                    "from_state",
                    "to_state",
                ),
                name="core_audit_request_transition_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="assurancerun",
            index=models.Index(
                fields=["organization", "repository_external_id", "pull_request_number"],
                name="core_assurance_pr_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_assurancerun_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "repository_external_id",
                    "pull_request_number",
                    "head_commit",
                ),
                name="core_assurance_one_head_summary",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=models.Q(("head_commit__regex", "^[a-f0-9]{7,64}$")),
                name="core_assurance_head_commit_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_version__gte", 1)),
                name="core_assurance_policy_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "COMPLETED"), _negated=True),
                    models.Q(
                        ("evaluated_commit", models.F("head_commit")),
                        ("report_commit", models.F("head_commit")),
                        ("completed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="core_assurance_completed_commit_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("state__in", ["COMPLETED", "STALE", "FAILED", "CANCELLED"]),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        (
                            "state__in",
                            [
                                "REQUESTED",
                                "DEBOUNCING",
                                "FETCHING_PULL_REQUEST",
                                "COLLECTING_EVIDENCE",
                                "EVALUATING_POLICY",
                                "BUILDING_CONTEXT",
                                "MODEL_REVIEW",
                                "MAPPING_EVIDENCE",
                                "RENDERING_REPORT",
                                "PUBLISHING",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="core_assurance_terminal_time_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["published_at", "available_at", "created_at"],
                name="core_outbox_dispatch_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="core_outbox_org_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="core_sourceconnection_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconnection",
            constraint=models.UniqueConstraint(
                fields=("organization", "external_key"),
                name="core_source_connection_org_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconnection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_connection_org_id_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(
                fields=["organization", "source_connection", "state"],
                name="core_sync_org_conn_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_syncrun_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "REQUESTED",
                            "DISCOVERING",
                            "FETCHING",
                            "PARSING",
                            "INDEXING",
                            "EXTRACTING",
                            "RESOLVING",
                            "PUBLISHING",
                        ],
                    )
                ),
                fields=("organization", "source_connection"),
                name="core_sync_one_active_per_connection",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("state__in", ["COMPLETED", "PARTIALLY_COMPLETED", "FAILED", "CANCELLED"]),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        (
                            "state__in",
                            [
                                "REQUESTED",
                                "DISCOVERING",
                                "FETCHING",
                                "PARSING",
                                "INDEXING",
                                "EXTRACTING",
                                "RESOLVING",
                                "PUBLISHING",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="core_sync_terminal_completion_coherent",
            ),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_syncrun
                ADD CONSTRAINT core_sync_org_connection_fk
                FOREIGN KEY (organization_id, source_connection_id)
                REFERENCES core_sourceconnection (organization_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE core_assurancerun
                ADD CONSTRAINT core_assurance_org_artifact_fk
                FOREIGN KEY (organization_id, context_artifact_id)
                REFERENCES core_immutableartifact (organization_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                CREATE FUNCTION core_reject_immutable_change()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME
                        USING ERRCODE = '55000';
                END;
                $$;

                CREATE TRIGGER core_artifact_immutable
                BEFORE UPDATE OR DELETE ON core_immutableartifact
                FOR EACH ROW EXECUTE FUNCTION core_reject_immutable_change();

                CREATE TRIGGER core_audit_immutable
                BEFORE UPDATE OR DELETE ON core_auditevent
                FOR EACH ROW EXECUTE FUNCTION core_reject_immutable_change();
            """,
            reverse_sql="""
                DROP TRIGGER core_audit_immutable ON core_auditevent;
                DROP TRIGGER core_artifact_immutable ON core_immutableartifact;
                DROP FUNCTION core_reject_immutable_change();
                ALTER TABLE core_assurancerun
                    DROP CONSTRAINT core_assurance_org_artifact_fk;
                ALTER TABLE core_syncrun
                    DROP CONSTRAINT core_sync_org_connection_fk;
            """,
        ),
    ]
