# Generated by Django 5.2.5 on 2026-07-28 01:00

# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONSHIPS = (
    ("core_knowledgeassertion", "access_scope_id", "core_accessscope"),
    ("core_immutableartifact", "access_scope_id", "core_accessscope"),
    ("core_membership", "role_id", "core_role"),
    ("core_teammembership", "team_id", "core_team"),
    ("core_teammembership", "membership_id", "core_membership"),
    ("core_accessscopesource", "access_scope_id", "core_accessscope"),
    ("core_accessscopesource", "source_connection_id", "core_sourceconnection"),
    ("core_accesssnapshot", "access_scope_id", "core_accessscope"),
    ("core_accesssnapshot", "source_connection_id", "core_sourceconnection"),
    ("core_accessscopemembership", "access_scope_id", "core_accessscope"),
    ("core_accessscopemembership", "membership_id", "core_membership"),
    ("core_accessscoperepository", "access_scope_id", "core_accessscope"),
    ("core_accessscoperepository", "repository_id", "core_repository"),
    ("core_accessscopeserviceidentity", "access_scope_id", "core_accessscope"),
    ("core_accessscopeserviceidentity", "service_identity_id", "core_serviceidentity"),
    ("core_accessgrant", "membership_id", "core_membership"),
    ("core_accessgrant", "service_identity_id", "core_serviceidentity"),
    ("core_accessgrant", "repository_id", "core_repository"),
    ("core_accessgrant", "source_connection_id", "core_sourceconnection"),
    ("core_repositoryaccesstoken", "repository_id", "core_repository"),
    ("core_repositoryaccesstoken", "service_identity_id", "core_serviceidentity"),
    ("core_repositoryaccesstoken", "rotated_from_id", "core_repositoryaccesstoken"),
)


def _constraint_name(table: str, column: str) -> str:
    return f"{table.removeprefix('core_')}_{column.removesuffix('_id')}_same_tenant_fk"


SAME_TENANT_SQL = "\n".join(
    (
        f"ALTER TABLE {table} ADD CONSTRAINT {_constraint_name(table, column)} "
        f"FOREIGN KEY (organization_id, {column}) "
        f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    )
    for table, column, target in SAME_TENANT_RELATIONSHIPS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {_constraint_name(table, column)};"
    for table, column, _target in reversed(SAME_TENANT_RELATIONSHIPS)
)

SCOPE_DERIVATION_TRIGGER_SQL = """
CREATE FUNCTION core_validate_scope_derivation_tenant() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM core_accessscope parent_scope
        JOIN core_accessscope child_scope
          ON child_scope.id = NEW.from_accessscope_id
         AND child_scope.organization_id = parent_scope.organization_id
        WHERE parent_scope.id = NEW.to_accessscope_id
    ) THEN
        RAISE EXCEPTION 'derived access scopes must belong to one organization'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER core_scope_derivation_same_tenant
BEFORE INSERT OR UPDATE ON core_accessscope_derived_from
FOR EACH ROW EXECUTE FUNCTION core_validate_scope_derivation_tenant();
"""
DROP_SCOPE_DERIVATION_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS core_scope_derivation_same_tenant ON core_accessscope_derived_from;
DROP FUNCTION IF EXISTS core_validate_scope_derivation_tenant();
"""

SNAPSHOT_IMMUTABILITY_TRIGGER_SQL = """
CREATE FUNCTION core_enforce_access_snapshot_immutable() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'access snapshots cannot be deleted'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.source_connection_id IS DISTINCT FROM OLD.source_connection_id
       OR NEW.access_scope_id IS DISTINCT FROM OLD.access_scope_id
       OR NEW.scope_revision IS DISTINCT FROM OLD.scope_revision
       OR NEW.payload IS DISTINCT FROM OLD.payload
       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
       OR NEW.captured_at IS DISTINCT FROM OLD.captured_at
       OR (OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at)
       OR (OLD.revoked_at IS NULL AND NEW.revoked_at IS NULL) THEN
        RAISE EXCEPTION 'access snapshots are immutable except for initial revocation'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER core_access_snapshot_immutable
BEFORE UPDATE OR DELETE ON core_accesssnapshot
FOR EACH ROW EXECUTE FUNCTION core_enforce_access_snapshot_immutable();
"""
DROP_SNAPSHOT_IMMUTABILITY_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS core_access_snapshot_immutable ON core_accesssnapshot;
DROP FUNCTION IF EXISTS core_enforce_access_snapshot_immutable();
"""

DERIVED_SCOPE_IMMUTABILITY_TRIGGER_SQL = """
CREATE FUNCTION core_enforce_derived_scope_boundary() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.is_derived THEN
            RAISE EXCEPTION 'derived access scope boundaries are immutable'
                USING ERRCODE = '23514';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.is_derived THEN
        IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
           OR NEW.all_memberships IS DISTINCT FROM OLD.all_memberships
           OR NEW.all_service_identities IS DISTINCT FROM OLD.all_service_identities
           OR NEW.all_repositories IS DISTINCT FROM OLD.all_repositories
           OR NEW.is_derived IS DISTINCT FROM OLD.is_derived
           OR NEW.boundary_sealed_at IS DISTINCT FROM OLD.boundary_sealed_at
           OR (NOT OLD.is_active AND NEW.is_active) THEN
            RAISE EXCEPTION 'derived access scope boundaries are immutable'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER core_derived_scope_boundary_immutable
BEFORE UPDATE OR DELETE ON core_accessscope
FOR EACH ROW EXECUTE FUNCTION core_enforce_derived_scope_boundary();

CREATE FUNCTION core_enforce_derived_scope_relation_immutable() RETURNS trigger AS $$
DECLARE
    scope_id uuid;
BEGIN
    IF TG_TABLE_NAME = 'core_accessscope_derived_from' THEN
        scope_id := CASE
            WHEN TG_OP = 'DELETE' THEN OLD.from_accessscope_id
            ELSE NEW.from_accessscope_id
        END;
    ELSE
        scope_id := CASE
            WHEN TG_OP = 'DELETE' THEN OLD.access_scope_id
            ELSE NEW.access_scope_id
        END;
    END IF;
    IF EXISTS (
        SELECT 1 FROM core_accessscope
        WHERE id = scope_id AND is_derived
    ) THEN
        RAISE EXCEPTION 'derived access scope relations are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER core_derived_scope_lineage_immutable
BEFORE INSERT OR UPDATE OR DELETE ON core_accessscope_derived_from
FOR EACH ROW EXECUTE FUNCTION core_enforce_derived_scope_relation_immutable();
CREATE TRIGGER core_derived_scope_membership_immutable
BEFORE INSERT OR UPDATE OR DELETE ON core_accessscopemembership
FOR EACH ROW EXECUTE FUNCTION core_enforce_derived_scope_relation_immutable();
CREATE TRIGGER core_derived_scope_service_immutable
BEFORE INSERT OR UPDATE OR DELETE ON core_accessscopeserviceidentity
FOR EACH ROW EXECUTE FUNCTION core_enforce_derived_scope_relation_immutable();
CREATE TRIGGER core_derived_scope_repository_immutable
BEFORE INSERT OR UPDATE OR DELETE ON core_accessscoperepository
FOR EACH ROW EXECUTE FUNCTION core_enforce_derived_scope_relation_immutable();
CREATE TRIGGER core_derived_scope_source_immutable
BEFORE INSERT OR UPDATE OR DELETE ON core_accessscopesource
FOR EACH ROW EXECUTE FUNCTION core_enforce_derived_scope_relation_immutable();
"""
DROP_DERIVED_SCOPE_IMMUTABILITY_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS core_derived_scope_source_immutable ON core_accessscopesource;
DROP TRIGGER IF EXISTS core_derived_scope_repository_immutable ON core_accessscoperepository;
DROP TRIGGER IF EXISTS core_derived_scope_service_immutable ON core_accessscopeserviceidentity;
DROP TRIGGER IF EXISTS core_derived_scope_membership_immutable ON core_accessscopemembership;
DROP TRIGGER IF EXISTS core_derived_scope_lineage_immutable ON core_accessscope_derived_from;
DROP FUNCTION IF EXISTS core_enforce_derived_scope_relation_immutable();
DROP TRIGGER IF EXISTS core_derived_scope_boundary_immutable ON core_accessscope;
DROP FUNCTION IF EXISTS core_enforce_derived_scope_boundary();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=320, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccessScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("all_memberships", models.BooleanField(default=False)),
                ("all_service_identities", models.BooleanField(default=False)),
                ("all_repositories", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_derived", models.BooleanField(default=False)),
                ("boundary_sealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "derived_from",
                    models.ManyToManyField(
                        blank=True, related_name="derived_scopes", to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="immutableartifact",
            name="access_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.accessscope",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="access_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.accessscope",
            ),
        ),
        migrations.CreateModel(
            name="AccessScopeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sourceconnection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scope_revision", models.PositiveBigIntegerField()),
                ("payload", models.JSONField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourceconnection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccessScopeMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.membership"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessScopeRepository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.repository"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ORG_ADMIN", "Org Admin"),
                            ("KNOWLEDGE_ADMIN", "Knowledge Admin"),
                            ("TECHNICAL_OWNER", "Technical Owner"),
                            ("PRODUCT_OWNER", "Product Owner"),
                            ("DEVELOPER", "Developer"),
                            ("REVIEWER", "Reviewer"),
                            ("SECURITY_REVIEWER", "Security Reviewer"),
                            ("VIEWER", "Viewer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.role"),
        ),
        migrations.CreateModel(
            name="ServiceIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("audience", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RepositoryAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64)),
                ("allowed_actions", models.JSONField()),
                ("issuer", models.CharField(max_length=200)),
                ("audience", models.CharField(max_length=200)),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
                (
                    "rotated_from",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rotated_to",
                        to="core.repositoryaccesstoken",
                    ),
                ),
                (
                    "service_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.serviceidentity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessScopeServiceIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "service_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.serviceidentity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.sourceconnection",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.membership",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.repository",
                    ),
                ),
                (
                    "service_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.serviceidentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.membership"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.team"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.user"),
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="accessscope",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_accessscope_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessscope",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_access_scope_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("boundary_sealed_at__isnull", True), ("is_derived", False)),
                    models.Q(("boundary_sealed_at__isnull", False), ("is_derived", True)),
                    _connector="OR",
                ),
                name="core_access_scope_derived_seal_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessscopesource",
            constraint=models.UniqueConstraint(
                fields=("access_scope", "source_connection"), name="core_scope_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="accesssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_revision__gte", 1)),
                name="core_access_snapshot_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_access_snapshot_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesssnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_connection", "content_hash"),
                name="core_access_snapshot_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessscopemembership",
            constraint=models.UniqueConstraint(
                fields=("access_scope", "membership"), name="core_scope_membership_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("organization", "external_id"), name="core_repository_org_external_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_repository_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessscoperepository",
            constraint=models.UniqueConstraint(
                fields=("access_scope", "repository"), name="core_scope_repository_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="core_role_org_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_role_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_serviceidentity_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceidentity",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="core_service_identity_org_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceidentity",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_service_identity_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repositoryaccesstoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("token_hash__regex", "^[a-f0-9]{64}$")),
                name="core_repository_token_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="repositoryaccesstoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                name="core_repository_token_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="repositoryaccesstoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("allowed_actions", []), _negated=True),
                name="core_repository_token_actions_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="repositoryaccesstoken",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_repository_token_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repositoryaccesstoken",
            constraint=models.UniqueConstraint(
                fields=("token_hash",), name="core_repository_token_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessscopeserviceidentity",
            constraint=models.UniqueConstraint(
                fields=("access_scope", "service_identity"), name="core_scope_service_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("membership__isnull", False), ("service_identity__isnull", True)),
                    models.Q(("membership__isnull", True), ("service_identity__isnull", False)),
                    _connector="OR",
                ),
                name="core_access_grant_one_principal",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.UniqueConstraint(
                fields=("organization", "membership", "repository", "source_connection", "action"),
                name="core_access_grant_membership_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "service_identity",
                    "repository",
                    "source_connection",
                    "action",
                ),
                name="core_access_grant_service_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="core_team_org_slug_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_team_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("organization", "team", "membership"), name="core_team_membership_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_membership_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="core_membership_org_user_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_membership_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"), name="core_external_identity_unique"
            ),
        ),
        migrations.RunSQL(sql=SAME_TENANT_SQL, reverse_sql=DROP_SAME_TENANT_SQL),
        migrations.RunSQL(
            sql=SCOPE_DERIVATION_TRIGGER_SQL,
            reverse_sql=DROP_SCOPE_DERIVATION_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=SNAPSHOT_IMMUTABILITY_TRIGGER_SQL,
            reverse_sql=DROP_SNAPSHOT_IMMUTABILITY_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=DERIVED_SCOPE_IMMUTABILITY_TRIGGER_SQL,
            reverse_sql=DROP_DERIVED_SCOPE_IMMUTABILITY_TRIGGER_SQL,
        ),
    ]
