# Generated by Django 5.2.5 on 2026-07-28 07:40

# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONSHIPS = (
    ("core_sourceconnection", "repository_id", "core_repository", "srcconn_repo_tenant_fk"),
    ("core_sourceconnection", "access_scope_id", "core_accessscope", "srcconn_scope_tenant_fk"),
    ("core_syncrun", "access_snapshot_id", "core_accesssnapshot", "sync_snapshot_tenant_fk"),
    (
        "core_sourcecontainer",
        "source_connection_id",
        "core_sourceconnection",
        "srccontainer_conn_tenant_fk",
    ),
    (
        "core_sourcedocument",
        "source_container_id",
        "core_sourcecontainer",
        "srcdoc_container_tenant_fk",
    ),
    (
        "core_sourcedocument",
        "current_revision_id",
        "core_sourcerevision",
        "srcdoc_revision_tenant_fk",
    ),
    ("core_sourcedocument", "last_seen_run_id", "core_syncrun", "srcdoc_run_tenant_fk"),
    (
        "core_sourcerevision",
        "source_document_id",
        "core_sourcedocument",
        "srcrev_document_tenant_fk",
    ),
    (
        "core_sourcerevision",
        "content_artifact_id",
        "core_sourcecontentartifact",
        "srcrev_content_tenant_fk",
    ),
    ("core_sourceobservation", "sync_run_id", "core_syncrun", "srcobs_run_tenant_fk"),
    (
        "core_sourceobservation",
        "source_document_id",
        "core_sourcedocument",
        "srcobs_document_tenant_fk",
    ),
    (
        "core_sourceobservation",
        "source_revision_id",
        "core_sourcerevision",
        "srcobs_revision_tenant_fk",
    ),
    (
        "core_sourceobservation",
        "access_snapshot_id",
        "core_accesssnapshot",
        "srcobs_snapshot_tenant_fk",
    ),
    (
        "core_parsedsource",
        "source_revision_id",
        "core_sourcerevision",
        "parsed_revision_tenant_fk",
    ),
    (
        "core_sourcelocation",
        "parsed_source_id",
        "core_parsedsource",
        "location_parsed_tenant_fk",
    ),
    (
        "core_sourcelocation",
        "source_observation_id",
        "core_sourceobservation",
        "location_observation_tenant_fk",
    ),
    (
        "core_extractionresult",
        "parsed_source_id",
        "core_parsedsource",
        "extract_parsed_tenant_fk",
    ),
    (
        "core_synccursor",
        "source_connection_id",
        "core_sourceconnection",
        "cursor_connection_tenant_fk",
    ),
    ("core_ingestionfailure", "sync_run_id", "core_syncrun", "failure_run_tenant_fk"),
    (
        "core_ingestionfailure",
        "source_document_id",
        "core_sourcedocument",
        "failure_document_tenant_fk",
    ),
    (
        "core_ingestionstageresult",
        "background_job_id",
        "core_backgroundjob",
        "stage_job_tenant_fk",
    ),
    (
        "core_ingestionstageresult",
        "sync_run_id",
        "core_syncrun",
        "stage_run_tenant_fk",
    ),
    (
        "core_assertionprovenance",
        "assertion_id",
        "core_knowledgeassertion",
        "assertprov_assertion_tenant_fk",
    ),
    (
        "core_assertionprovenance",
        "source_location_id",
        "core_sourcelocation",
        "assertprov_location_tenant_fk",
    ),
    (
        "core_assertionprovenance",
        "source_observation_id",
        "core_sourceobservation",
        "assertprov_observation_tenant_fk",
    ),
    (
        "core_assertionprovenance",
        "access_snapshot_id",
        "core_accesssnapshot",
        "assertprov_snapshot_tenant_fk",
    ),
    (
        "core_assertionvalidityinterval",
        "assertion_id",
        "core_knowledgeassertion",
        "assertint_assertion_tenant_fk",
    ),
    (
        "core_assertionvalidityinterval",
        "source_document_id",
        "core_sourcedocument",
        "assertint_document_tenant_fk",
    ),
    (
        "core_assertionvalidityinterval",
        "source_observation_id",
        "core_sourceobservation",
        "assertint_observation_tenant_fk",
    ),
    (
        "core_assertionrevision",
        "assertion_id",
        "core_knowledgeassertion",
        "assertrev_assertion_tenant_fk",
    ),
    (
        "core_assertionreview",
        "assertion_id",
        "core_knowledgeassertion",
        "assertreview_assertion_tenant_fk",
    ),
    (
        "core_assertionconflict",
        "left_assertion_id",
        "core_knowledgeassertion",
        "conflict_left_tenant_fk",
    ),
    (
        "core_assertionconflict",
        "right_assertion_id",
        "core_knowledgeassertion",
        "conflict_right_tenant_fk",
    ),
    (
        "core_knowledgeentity",
        "access_scope_id",
        "core_accessscope",
        "entity_scope_tenant_fk",
    ),
    ("core_entityalias", "entity_id", "core_knowledgeentity", "alias_entity_tenant_fk"),
    (
        "core_entityalias",
        "source_location_id",
        "core_sourcelocation",
        "alias_location_tenant_fk",
    ),
    (
        "core_entityresolution",
        "source_location_id",
        "core_sourcelocation",
        "resolution_location_tenant_fk",
    ),
    (
        "core_entityresolution",
        "entity_id",
        "core_knowledgeentity",
        "resolution_entity_tenant_fk",
    ),
)

SAME_TENANT_SQL = "\n".join(
    (
        f"ALTER TABLE {table} ADD CONSTRAINT {name} "
        f"FOREIGN KEY (organization_id, {column}) "
        f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    )
    for table, column, target, name in SAME_TENANT_RELATIONSHIPS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name};"
    for table, _column, _target, name in reversed(SAME_TENANT_RELATIONSHIPS)
)

IMMUTABLE_TABLES = (
    "core_sourcecontentartifact",
    "core_sourcerevision",
    "core_sourceobservation",
    "core_parsedsource",
    "core_sourcelocation",
    "core_extractionresult",
    "core_assertionprovenance",
    "core_assertionrevision",
    "core_assertionreview",
    "core_entityresolution",
)
IMMUTABILITY_TRIGGER_SQL = """
CREATE FUNCTION core_reject_immutable_history_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is immutable', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
""" + "\n".join(
    f"""
CREATE TRIGGER {table.removeprefix("core_")}_immutable
BEFORE UPDATE OR DELETE ON {table}
FOR EACH ROW EXECUTE FUNCTION core_reject_immutable_history_change();
"""
    for table in IMMUTABLE_TABLES
)
DROP_IMMUTABILITY_TRIGGER_SQL = (
    "\n".join(
        f"DROP TRIGGER IF EXISTS {table.removeprefix('core_')}_immutable ON {table};"
        for table in reversed(IMMUTABLE_TABLES)
    )
    + "\nDROP FUNCTION IF EXISTS core_reject_immutable_history_change();"
)

TEMPORAL_IMMUTABILITY_TRIGGER_SQL = """
CREATE FUNCTION core_enforce_assertion_interval_close_once() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'assertion validity intervals cannot be deleted'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.assertion_id IS DISTINCT FROM OLD.assertion_id
       OR NEW.source_document_id IS DISTINCT FROM OLD.source_document_id
       OR NEW.source_observation_id IS DISTINCT FROM OLD.source_observation_id
       OR NEW.valid_from IS DISTINCT FROM OLD.valid_from
       OR NEW.observed_from IS DISTINCT FROM OLD.observed_from
       OR OLD.valid_until IS NOT NULL
       OR OLD.observed_until IS NOT NULL
       OR NEW.valid_until IS NULL
       OR NEW.observed_until IS NULL THEN
        RAISE EXCEPTION 'assertion validity intervals may only be closed once'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER assertionvalidityinterval_close_once
BEFORE UPDATE OR DELETE ON core_assertionvalidityinterval
FOR EACH ROW EXECUTE FUNCTION core_enforce_assertion_interval_close_once();
"""
DROP_TEMPORAL_IMMUTABILITY_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS assertionvalidityinterval_close_once
    ON core_assertionvalidityinterval;
DROP FUNCTION IF EXISTS core_enforce_assertion_interval_close_once();
"""

PROVENANCE_ALIGNMENT_TRIGGER_SQL = """
CREATE FUNCTION core_validate_source_content() RETURNS trigger AS $$
BEGIN
    IF NEW.byte_size <> octet_length(NEW.content) THEN
        RAISE EXCEPTION 'source content byte size does not match bytes'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_source_revision() RETURNS trigger AS $$
DECLARE
    artifact_hash text;
BEGIN
    SELECT content_hash INTO artifact_hash
      FROM core_sourcecontentartifact
     WHERE id = NEW.content_artifact_id
       AND organization_id = NEW.organization_id;
    IF artifact_hash IS NULL OR NEW.content_hash <> artifact_hash THEN
        RAISE EXCEPTION 'source revision content identity is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_source_document() RETURNS trigger AS $$
BEGIN
    IF NEW.current_revision_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM core_sourcerevision
         WHERE id = NEW.current_revision_id
           AND organization_id = NEW.organization_id
           AND source_document_id = NEW.id
    ) THEN
        RAISE EXCEPTION 'current revision must belong to the source document'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_source_observation() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM core_syncrun run
          JOIN core_sourceconnection connection
            ON connection.id = run.source_connection_id
           AND connection.organization_id = run.organization_id
          JOIN core_sourcecontainer container
            ON container.source_connection_id = connection.id
           AND container.organization_id = connection.organization_id
          JOIN core_sourcedocument document
            ON document.source_container_id = container.id
           AND document.organization_id = container.organization_id
          JOIN core_accesssnapshot snapshot
            ON snapshot.id = NEW.access_snapshot_id
           AND snapshot.source_connection_id = connection.id
           AND snapshot.organization_id = connection.organization_id
         WHERE run.id = NEW.sync_run_id
           AND document.id = NEW.source_document_id
           AND run.access_snapshot_id = NEW.access_snapshot_id
           AND run.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'observation source, run, and access snapshot are inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_revision_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM core_sourcerevision revision
         WHERE revision.id = NEW.source_revision_id
           AND revision.organization_id = NEW.organization_id
           AND revision.source_document_id = NEW.source_document_id
    ) THEN
        RAISE EXCEPTION 'observation revision does not match document'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_parsed_source() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM core_sourcerevision revision
          JOIN core_sourcedocument document
            ON document.id = revision.source_document_id
           AND document.organization_id = revision.organization_id
         WHERE revision.id = NEW.source_revision_id
           AND revision.organization_id = NEW.organization_id
           AND document.document_kind = NEW.document_kind
    ) THEN
        RAISE EXCEPTION 'parser output kind does not match source document'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_source_location() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM core_parsedsource parsed
          JOIN core_sourceobservation observation
            ON observation.source_revision_id = parsed.source_revision_id
           AND observation.organization_id = parsed.organization_id
         WHERE parsed.id = NEW.parsed_source_id
           AND observation.id = NEW.source_observation_id
           AND parsed.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'source location derivation and observation are inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_assertion_provenance() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM core_sourcelocation location
          JOIN core_sourceobservation observation
            ON observation.id = location.source_observation_id
           AND observation.organization_id = location.organization_id
         WHERE location.id = NEW.source_location_id
           AND observation.id = NEW.source_observation_id
           AND observation.access_snapshot_id = NEW.access_snapshot_id
           AND location.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'assertion provenance lineage is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_validate_assertion_interval() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM core_sourceobservation observation
         WHERE observation.id = NEW.source_observation_id
           AND observation.organization_id = NEW.organization_id
           AND observation.source_document_id = NEW.source_document_id
    ) THEN
        RAISE EXCEPTION 'assertion interval observation does not match document'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER sourcecontentartifact_validate
BEFORE INSERT ON core_sourcecontentartifact
FOR EACH ROW EXECUTE FUNCTION core_validate_source_content();
CREATE TRIGGER sourcerevision_validate
BEFORE INSERT ON core_sourcerevision
FOR EACH ROW EXECUTE FUNCTION core_validate_source_revision();
CREATE TRIGGER sourcedocument_validate
BEFORE INSERT OR UPDATE ON core_sourcedocument
FOR EACH ROW EXECUTE FUNCTION core_validate_source_document();
CREATE TRIGGER sourceobservation_validate
BEFORE INSERT ON core_sourceobservation
FOR EACH ROW EXECUTE FUNCTION core_validate_source_observation();
CREATE TRIGGER parsedsource_validate
BEFORE INSERT ON core_parsedsource
FOR EACH ROW EXECUTE FUNCTION core_validate_parsed_source();
CREATE TRIGGER sourcelocation_validate
BEFORE INSERT ON core_sourcelocation
FOR EACH ROW EXECUTE FUNCTION core_validate_source_location();
CREATE TRIGGER assertionprovenance_validate
BEFORE INSERT ON core_assertionprovenance
FOR EACH ROW EXECUTE FUNCTION core_validate_assertion_provenance();
CREATE TRIGGER assertionvalidityinterval_validate
BEFORE INSERT OR UPDATE ON core_assertionvalidityinterval
FOR EACH ROW EXECUTE FUNCTION core_validate_assertion_interval();
"""
DROP_PROVENANCE_ALIGNMENT_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS assertionvalidityinterval_validate
    ON core_assertionvalidityinterval;
DROP TRIGGER IF EXISTS assertionprovenance_validate ON core_assertionprovenance;
DROP TRIGGER IF EXISTS sourcelocation_validate ON core_sourcelocation;
DROP TRIGGER IF EXISTS parsedsource_validate ON core_parsedsource;
DROP TRIGGER IF EXISTS sourceobservation_validate ON core_sourceobservation;
DROP TRIGGER IF EXISTS sourcedocument_validate ON core_sourcedocument;
DROP TRIGGER IF EXISTS sourcerevision_validate ON core_sourcerevision;
DROP TRIGGER IF EXISTS sourcecontentartifact_validate ON core_sourcecontentartifact;
DROP FUNCTION IF EXISTS core_validate_assertion_interval();
DROP FUNCTION IF EXISTS core_validate_assertion_provenance();
DROP FUNCTION IF EXISTS core_validate_source_location();
DROP FUNCTION IF EXISTS core_validate_parsed_source();
DROP FUNCTION IF EXISTS core_validate_source_observation();
DROP FUNCTION IF EXISTS core_validate_source_document();
DROP FUNCTION IF EXISTS core_validate_source_revision();
DROP FUNCTION IF EXISTS core_validate_source_content();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_accessscope_immutableartifact_access_scope_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssertionConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("predicate", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssertionProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extraction_class",
                    models.CharField(
                        choices=[
                            ("MECHANICAL", "Mechanical"),
                            ("INTERPRETIVE", "Interpretive"),
                            ("HUMAN", "Human"),
                        ],
                        max_length=20,
                    ),
                ),
                ("extraction_method", models.CharField(max_length=200)),
                ("confidence", models.FloatField()),
                ("is_inferred", models.BooleanField(default=False)),
                ("observed_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AssertionReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_type", models.CharField(max_length=50)),
                ("actor_id", models.CharField(max_length=200)),
                ("from_state", models.CharField(max_length=24)),
                ("to_state", models.CharField(max_length=24)),
                ("assertion_revision", models.PositiveBigIntegerField()),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("reviewed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="AssertionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssertionValidityInterval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("observed_from", models.DateTimeField()),
                ("observed_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("normalized_alias", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="EntityResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("candidate_key", models.CharField(max_length=500)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched"),
                            ("CREATED", "Created"),
                            ("AMBIGUOUS", "Ambiguous"),
                            ("CONFLICT", "Conflict"),
                            ("IGNORED", "Ignored"),
                        ],
                        max_length=16,
                    ),
                ),
                ("candidate_ids", models.JSONField(default=list)),
                ("resolver_version", models.CharField(max_length=50)),
                ("resolved_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("extractor_name", models.CharField(max_length=100)),
                ("extractor_version", models.CharField(max_length=50)),
                ("claims", models.JSONField()),
                ("output_hash", models.CharField(max_length=64)),
                ("duration_ms", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionFailure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.CharField(max_length=50)),
                ("item_key", models.CharField(max_length=1000)),
                ("error_code", models.CharField(max_length=100)),
                ("safe_message", models.CharField(max_length=500)),
                ("is_transient", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionStageResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.CharField(max_length=50)),
                ("input_version", models.CharField(max_length=100)),
                ("implementation_version", models.CharField(max_length=100)),
                ("output_version", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("TEAM", "Team"),
                            ("REPOSITORY", "Repository"),
                            ("SERVICE", "Service"),
                            ("COMPONENT", "Component"),
                            ("API", "Api"),
                            ("DATA_ASSET", "Data Asset"),
                            ("DECISION", "Decision"),
                            ("POLICY", "Policy"),
                            ("REQUIREMENT", "Requirement"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("canonical_key", models.CharField(max_length=500)),
                ("display_name", models.CharField(max_length=500)),
                ("attributes", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParsedSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("parser_name", models.CharField(max_length=100)),
                ("parser_version", models.CharField(max_length=50)),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("MARKDOWN", "Markdown"),
                            ("YAML", "Yaml"),
                            ("JSON", "Json"),
                            ("TEXT", "Text"),
                            ("CODEOWNERS", "Codeowners"),
                            ("MANIFEST", "Manifest"),
                            ("MIGRATION", "Migration"),
                            ("WORKFLOW", "Workflow"),
                            ("OPENAPI", "Openapi"),
                        ],
                        max_length=32,
                    ),
                ),
                ("normalized", models.JSONField()),
                ("output_hash", models.CharField(max_length=64)),
                ("duration_ms", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceContainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=500)),
                ("name", models.CharField(max_length=300)),
                ("canonical_url", models.CharField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("first_observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_observed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="SourceContentArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("byte_size", models.PositiveIntegerField()),
                ("media_type", models.CharField(max_length=200)),
                ("content", models.BinaryField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=1000)),
                ("relative_path", models.CharField(max_length=1000)),
                ("canonical_url", models.CharField(max_length=1500)),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("MARKDOWN", "Markdown"),
                            ("YAML", "Yaml"),
                            ("JSON", "Json"),
                            ("TEXT", "Text"),
                            ("CODEOWNERS", "Codeowners"),
                            ("MANIFEST", "Manifest"),
                            ("MIGRATION", "Migration"),
                            ("WORKFLOW", "Workflow"),
                            ("OPENAPI", "Openapi"),
                        ],
                        max_length=32,
                    ),
                ),
                ("media_type", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[("PRESENT", "Present"), ("TOMBSTONED", "Tombstoned")],
                        default="PRESENT",
                        max_length=16,
                    ),
                ),
                ("first_observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("tombstoned_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pointer", models.CharField(max_length=1000)),
                ("start_line", models.PositiveIntegerField(blank=True, null=True)),
                ("end_line", models.PositiveIntegerField(blank=True, null=True)),
                ("excerpt_hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="SourceObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("TOMBSTONED", "Tombstoned"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("error_code", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SourceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("canonical_url", models.CharField(max_length=1500)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("cursor_key", models.CharField(max_length=100)),
                ("cursor_value", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="confidence",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="extraction_class",
            field=models.CharField(
                choices=[
                    ("MECHANICAL", "Mechanical"),
                    ("INTERPRETIVE", "Interpretive"),
                    ("HUMAN", "Human"),
                ],
                default="HUMAN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="extraction_method",
            field=models.CharField(default="human", max_length=200),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="observed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="staleness_state",
            field=models.CharField(
                choices=[
                    ("FRESH", "Fresh"),
                    ("AGING", "Aging"),
                    ("STALE", "Stale"),
                    ("CONTRADICTED", "Contradicted"),
                    ("SOURCE_UNAVAILABLE", "Source Unavailable"),
                ],
                default="FRESH",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="knowledgeassertion",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="access_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.accessscope",
            ),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="configuration",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="connector_kind",
            field=models.CharField(
                choices=[("FILESYSTEM", "Filesystem")], default="FILESYSTEM", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="display_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="last_successful_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceconnection",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.repository",
            ),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="access_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.accesssnapshot",
            ),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="discovered_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="failed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="processed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="scan_mode",
            field=models.CharField(
                choices=[("FULL", "Full"), ("INCREMENTAL", "Incremental")],
                default="FULL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="tombstoned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="accesssnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_access_snapshot_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_background_job_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeassertion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_assertion_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="core_assertion_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="core_assertion_validity_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_sync_run_org_id_unique"
            ),
        ),
        migrations.AddField(
            model_name="assertionconflict",
            name="left_assertion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="left_conflicts",
                to="core.knowledgeassertion",
            ),
        ),
        migrations.AddField(
            model_name="assertionconflict",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="assertionconflict",
            name="right_assertion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="right_conflicts",
                to="core.knowledgeassertion",
            ),
        ),
        migrations.AddField(
            model_name="assertionprovenance",
            name="access_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.accesssnapshot"
            ),
        ),
        migrations.AddField(
            model_name="assertionprovenance",
            name="assertion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeassertion"
            ),
        ),
        migrations.AddField(
            model_name="assertionprovenance",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="assertionreview",
            name="assertion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeassertion"
            ),
        ),
        migrations.AddField(
            model_name="assertionreview",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="assertionrevision",
            name="assertion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeassertion"
            ),
        ),
        migrations.AddField(
            model_name="assertionrevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="assertionvalidityinterval",
            name="assertion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeassertion"
            ),
        ),
        migrations.AddField(
            model_name="assertionvalidityinterval",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="entityalias",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="entityresolution",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="ingestionfailure",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="ingestionfailure",
            name="sync_run",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.syncrun"),
        ),
        migrations.AddField(
            model_name="ingestionstageresult",
            name="background_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.backgroundjob",
            ),
        ),
        migrations.AddField(
            model_name="ingestionstageresult",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="ingestionstageresult",
            name="sync_run",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.syncrun"),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="access_scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="entityresolution",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.knowledgeentity",
            ),
        ),
        migrations.AddField(
            model_name="entityalias",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeentity"
            ),
        ),
        migrations.AddField(
            model_name="parsedsource",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="parsed_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.parsedsource"
            ),
        ),
        migrations.AddField(
            model_name="sourcecontainer",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcecontainer",
            name="source_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourceconnection"
            ),
        ),
        migrations.AddField(
            model_name="sourcecontentartifact",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seen_documents",
                to="core.syncrun",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="source_container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcecontainer"
            ),
        ),
        migrations.AddField(
            model_name="ingestionfailure",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.sourcedocument",
            ),
        ),
        migrations.AddField(
            model_name="assertionvalidityinterval",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="sourcelocation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcelocation",
            name="parsed_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.parsedsource"
            ),
        ),
        migrations.AddField(
            model_name="entityresolution",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcelocation"
            ),
        ),
        migrations.AddField(
            model_name="entityalias",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcelocation"
            ),
        ),
        migrations.AddField(
            model_name="assertionprovenance",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcelocation"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="access_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.accesssnapshot"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="sync_run",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.syncrun"),
        ),
        migrations.AddField(
            model_name="sourcelocation",
            name="source_observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourceobservation"
            ),
        ),
        migrations.AddField(
            model_name="assertionvalidityinterval",
            name="source_observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourceobservation"
            ),
        ),
        migrations.AddField(
            model_name="assertionprovenance",
            name="source_observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourceobservation"
            ),
        ),
        migrations.AddField(
            model_name="sourcerevision",
            name="content_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcecontentartifact"
            ),
        ),
        migrations.AddField(
            model_name="sourcerevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcerevision",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="source_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.sourcerevision",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.sourcerevision",
            ),
        ),
        migrations.AddField(
            model_name="parsedsource",
            name="source_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourcerevision"
            ),
        ),
        migrations.AddField(
            model_name="synccursor",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="synccursor",
            name="source_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sourceconnection"
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionconflict",
            constraint=models.UniqueConstraint(
                fields=("organization", "left_assertion", "right_assertion"),
                name="core_assertion_conflict_pair_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resolved_at__isnull", True), ("status", "OPEN")),
                    models.Q(("resolved_at__isnull", False), ("status", "RESOLVED")),
                    _connector="OR",
                ),
                name="core_assertion_conflict_resolution_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(("left_assertion", models.F("right_assertion")), _negated=True),
                name="core_assertion_conflict_distinct",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionreview",
            constraint=models.UniqueConstraint(
                fields=("organization", "assertion", "assertion_revision"),
                name="core_assertion_review_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "assertion", "revision"),
                name="core_assertion_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_assertion_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionstageresult",
            constraint=models.UniqueConstraint(
                fields=("organization", "sync_run", "stage", "implementation_version"),
                name="core_ingestion_stage_run_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionstageresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", True), ("status", "RUNNING")),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("status__in", ["SUCCEEDED", "PARTIAL", "FAILED"]),
                    ),
                    _connector="OR",
                ),
                name="core_ingestion_stage_completion_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_knowledgeentity_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.UniqueConstraint(
                fields=("organization", "entity_type", "canonical_key"),
                name="core_knowledge_entity_canonical_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_knowledge_entity_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionresult",
            constraint=models.UniqueConstraint(
                fields=("organization", "parsed_source", "extractor_name", "extractor_version"),
                name="core_extraction_result_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionresult",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_extraction_result_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_hash__regex", "^[a-f0-9]{64}$")),
                name="core_extraction_result_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecontainer",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_connection", "external_id"),
                name="core_source_container_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecontainer",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_container_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecontentartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "content_hash"), name="core_source_content_org_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecontentartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_content_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecontentartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_source_content_hash_sha256",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionfailure",
            index=models.Index(
                fields=["organization", "sync_run", "stage"], name="core_ing_fail_run_stage_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionfailure",
            constraint=models.UniqueConstraint(
                fields=("organization", "sync_run", "stage", "item_key", "error_code"),
                name="core_ingestion_failure_item_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityresolution",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_location", "candidate_key", "resolver_version"),
                name="core_entity_resolution_input_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityresolution",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_entity_resolution_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityalias",
            constraint=models.UniqueConstraint(
                fields=("organization", "entity", "normalized_alias"),
                name="core_entity_alias_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcelocation",
            constraint=models.UniqueConstraint(
                fields=("organization", "parsed_source", "source_observation", "pointer"),
                name="core_source_location_pointer_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcelocation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_location_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcelocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("excerpt_hash__regex", "^[a-f0-9]{64}$")),
                name="core_source_location_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcelocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_line__isnull", True), ("start_line__isnull", True)),
                    models.Q(
                        ("end_line__gte", models.F("start_line")),
                        ("end_line__isnull", False),
                        ("start_line__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="core_source_location_lines_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionvalidityinterval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("valid_until__isnull", True)),
                fields=("organization", "assertion", "source_document"),
                name="core_assertion_one_active_document_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionvalidityinterval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("observed_until__isnull", True), ("valid_until__isnull", True)),
                    models.Q(
                        ("observed_until__gte", models.F("observed_from")),
                        ("observed_until__isnull", False),
                        ("valid_until__gt", models.F("valid_from")),
                        ("valid_until__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="core_assertion_interval_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionprovenance",
            constraint=models.UniqueConstraint(
                fields=("organization", "assertion", "source_location"),
                name="core_assertion_provenance_location_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionprovenance",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="core_assertion_provenance_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_document", "content_hash"),
                name="core_source_revision_document_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_revision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_source_revision_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceobservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "sync_run", "source_document"),
                name="core_source_observation_run_document_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceobservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_observation_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("error_code", ""),
                        ("source_revision__isnull", False),
                        ("status", "PRESENT"),
                    ),
                    models.Q(
                        ("error_code", ""),
                        ("source_revision__isnull", True),
                        ("status", "TOMBSTONED"),
                    ),
                    models.Q(("source_revision__isnull", True), ("status", "FAILED")),
                    _connector="OR",
                ),
                name="core_source_observation_status_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["organization", "source_container", "state"],
                name="core_src_doc_cont_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_container", "external_id"),
                name="core_source_document_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_document_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "PRESENT"), ("tombstoned_at__isnull", True)),
                    models.Q(("state", "TOMBSTONED"), ("tombstoned_at__isnull", False)),
                    _connector="OR",
                ),
                name="core_source_document_tombstone_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="parsedsource",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_revision", "parser_name", "parser_version"),
                name="core_parsed_source_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="parsedsource",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_parsed_source_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="parsedsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_hash__regex", "^[a-f0-9]{64}$")),
                name="core_parsed_source_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="synccursor",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_synccursor_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="synccursor",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_connection", "cursor_key"),
                name="core_sync_cursor_connection_key_unique",
            ),
        ),
        migrations.RunSQL(sql=SAME_TENANT_SQL, reverse_sql=DROP_SAME_TENANT_SQL),
        migrations.RunSQL(
            sql=PROVENANCE_ALIGNMENT_TRIGGER_SQL,
            reverse_sql=DROP_PROVENANCE_ALIGNMENT_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=IMMUTABILITY_TRIGGER_SQL,
            reverse_sql=DROP_IMMUTABILITY_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=TEMPORAL_IMMUTABILITY_TRIGGER_SQL,
            reverse_sql=DROP_TEMPORAL_IMMUTABILITY_TRIGGER_SQL,
        ),
    ]
