# Generated by Django 5.2.5 on 2026-07-28 08:09

# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONSHIPS = (
    (
        "core_sourcechunk",
        "parsed_source_id",
        "core_parsedsource",
        "chunk_parsed_tenant_fk",
    ),
    (
        "core_sourcechunkvisibility",
        "source_chunk_id",
        "core_sourcechunk",
        "chunkvis_chunk_tenant_fk",
    ),
    (
        "core_sourcechunkvisibility",
        "source_location_id",
        "core_sourcelocation",
        "chunkvis_location_tenant_fk",
    ),
    (
        "core_sourcechunkvisibility",
        "source_observation_id",
        "core_sourceobservation",
        "chunkvis_observation_tenant_fk",
    ),
    (
        "core_sourcechunkvisibility",
        "access_snapshot_id",
        "core_accesssnapshot",
        "chunkvis_snapshot_tenant_fk",
    ),
    (
        "core_sourcechunkvisibility",
        "access_scope_id",
        "core_accessscope",
        "chunkvis_scope_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "source_entity_id",
        "core_knowledgeentity",
        "relation_source_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "target_entity_id",
        "core_knowledgeentity",
        "relation_target_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "assertion_id",
        "core_knowledgeassertion",
        "relation_assertion_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "source_location_id",
        "core_sourcelocation",
        "relation_location_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "source_observation_id",
        "core_sourceobservation",
        "relation_observation_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "access_snapshot_id",
        "core_accesssnapshot",
        "relation_snapshot_tenant_fk",
    ),
    (
        "core_knowledgerelationship",
        "access_scope_id",
        "core_accessscope",
        "relation_scope_tenant_fk",
    ),
)
SAME_TENANT_SQL = "\n".join(
    (
        f"ALTER TABLE {table} ADD CONSTRAINT {name} "
        f"FOREIGN KEY (organization_id, {column}) "
        f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    )
    for table, column, target, name in SAME_TENANT_RELATIONSHIPS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name};"
    for table, _column, _target, name in reversed(SAME_TENANT_RELATIONSHIPS)
)

CHUNK_TRIGGER_SQL = """
CREATE FUNCTION core_validate_source_chunk() RETURNS trigger AS $$
BEGIN
    IF NEW.char_count <> char_length(NEW.text) THEN
        RAISE EXCEPTION 'source chunk character count does not match text'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_reject_source_chunk_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'source chunks are immutable' USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER sourcechunk_validate
BEFORE INSERT ON core_sourcechunk
FOR EACH ROW EXECUTE FUNCTION core_validate_source_chunk();
CREATE TRIGGER sourcechunk_immutable
BEFORE UPDATE OR DELETE ON core_sourcechunk
FOR EACH ROW EXECUTE FUNCTION core_reject_source_chunk_change();
"""
DROP_CHUNK_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS sourcechunk_immutable ON core_sourcechunk;
DROP TRIGGER IF EXISTS sourcechunk_validate ON core_sourcechunk;
DROP FUNCTION IF EXISTS core_reject_source_chunk_change();
DROP FUNCTION IF EXISTS core_validate_source_chunk();
"""

VISIBILITY_TRIGGER_SQL = """
CREATE FUNCTION core_validate_chunk_visibility() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM core_sourcechunk chunk
          JOIN core_sourcelocation location
            ON location.parsed_source_id = chunk.parsed_source_id
           AND location.organization_id = chunk.organization_id
          JOIN core_sourceobservation observation
            ON observation.id = location.source_observation_id
           AND observation.organization_id = location.organization_id
          JOIN core_accesssnapshot snapshot
            ON snapshot.id = observation.access_snapshot_id
           AND snapshot.organization_id = observation.organization_id
         WHERE chunk.id = NEW.source_chunk_id
           AND location.id = NEW.source_location_id
           AND observation.id = NEW.source_observation_id
           AND snapshot.id = NEW.access_snapshot_id
           AND snapshot.access_scope_id = NEW.access_scope_id
           AND chunk.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'source chunk visibility lineage is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_enforce_chunk_visibility_close_once() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'source chunk visibility cannot be deleted'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.source_chunk_id IS DISTINCT FROM OLD.source_chunk_id
       OR NEW.source_location_id IS DISTINCT FROM OLD.source_location_id
       OR NEW.source_observation_id IS DISTINCT FROM OLD.source_observation_id
       OR NEW.access_snapshot_id IS DISTINCT FROM OLD.access_snapshot_id
       OR NEW.access_scope_id IS DISTINCT FROM OLD.access_scope_id
       OR NEW.observed_at IS DISTINCT FROM OLD.observed_at
       OR OLD.state <> 'AVAILABLE'
       OR OLD.revoked_at IS NOT NULL
       OR NEW.state = 'AVAILABLE'
       OR NEW.revoked_at IS NULL THEN
        RAISE EXCEPTION 'source chunk visibility may only be closed once'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER chunkvisibility_validate
BEFORE INSERT OR UPDATE ON core_sourcechunkvisibility
FOR EACH ROW EXECUTE FUNCTION core_validate_chunk_visibility();
CREATE TRIGGER chunkvisibility_close_once
BEFORE UPDATE OR DELETE ON core_sourcechunkvisibility
FOR EACH ROW EXECUTE FUNCTION core_enforce_chunk_visibility_close_once();
"""
DROP_VISIBILITY_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS chunkvisibility_close_once ON core_sourcechunkvisibility;
DROP TRIGGER IF EXISTS chunkvisibility_validate ON core_sourcechunkvisibility;
DROP FUNCTION IF EXISTS core_enforce_chunk_visibility_close_once();
DROP FUNCTION IF EXISTS core_validate_chunk_visibility();
"""

RELATIONSHIP_TRIGGER_SQL = """
CREATE FUNCTION core_validate_knowledge_relationship() RETURNS trigger AS $$
DECLARE
    actual_source_type text;
    actual_target_type text;
BEGIN
    SELECT entity_type INTO actual_source_type
      FROM core_knowledgeentity
     WHERE id = NEW.source_entity_id
       AND organization_id = NEW.organization_id;
    SELECT entity_type INTO actual_target_type
      FROM core_knowledgeentity
     WHERE id = NEW.target_entity_id
       AND organization_id = NEW.organization_id;
    IF actual_source_type IS NULL
       OR actual_target_type IS NULL
       OR actual_source_type <> NEW.source_entity_type
       OR actual_target_type <> NEW.target_entity_type THEN
        RAISE EXCEPTION 'relationship endpoint types do not match entities'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.relationship_type IN ('OWNED_BY', 'MAINTAINED_BY')
       AND (
           NEW.source_entity_type NOT IN (
               'SERVICE', 'COMPONENT', 'REPOSITORY', 'API', 'DATA_ASSET', 'UNKNOWN'
           )
           OR NEW.target_entity_type NOT IN ('TEAM', 'UNKNOWN')
       ) THEN
        RAISE EXCEPTION 'relationship endpoint types are invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.relationship_type = 'DEPENDS_ON'
       AND (
           NEW.source_entity_type NOT IN (
               'SERVICE', 'COMPONENT', 'API', 'DATA_ASSET', 'UNKNOWN'
           )
           OR NEW.target_entity_type NOT IN (
               'SERVICE', 'COMPONENT', 'API', 'DATA_ASSET', 'UNKNOWN'
           )
       ) THEN
        RAISE EXCEPTION 'relationship endpoint types are invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM core_assertionprovenance provenance
          JOIN core_sourcelocation location
            ON location.id = provenance.source_location_id
           AND location.organization_id = provenance.organization_id
          JOIN core_sourceobservation observation
            ON observation.id = provenance.source_observation_id
           AND observation.organization_id = provenance.organization_id
          JOIN core_accesssnapshot snapshot
            ON snapshot.id = provenance.access_snapshot_id
           AND snapshot.organization_id = provenance.organization_id
          JOIN core_knowledgeassertion assertion
            ON assertion.id = provenance.assertion_id
           AND assertion.organization_id = provenance.organization_id
         WHERE assertion.id = NEW.assertion_id
           AND location.id = NEW.source_location_id
           AND observation.id = NEW.source_observation_id
           AND snapshot.id = NEW.access_snapshot_id
           AND assertion.access_scope_id = NEW.access_scope_id
           AND provenance.extraction_class = NEW.extraction_class
           AND provenance.confidence = NEW.confidence
           AND provenance.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'relationship provenance and visibility are inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_reject_knowledge_relationship_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'knowledge relationships are immutable'
        USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledgerelationship_validate
BEFORE INSERT ON core_knowledgerelationship
FOR EACH ROW EXECUTE FUNCTION core_validate_knowledge_relationship();
CREATE TRIGGER knowledgerelationship_immutable
BEFORE UPDATE OR DELETE ON core_knowledgerelationship
FOR EACH ROW EXECUTE FUNCTION core_reject_knowledge_relationship_change();
"""
DROP_RELATIONSHIP_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS knowledgerelationship_immutable
    ON core_knowledgerelationship;
DROP TRIGGER IF EXISTS knowledgerelationship_validate
    ON core_knowledgerelationship;
DROP FUNCTION IF EXISTS core_reject_knowledge_relationship_change();
DROP FUNCTION IF EXISTS core_validate_knowledge_relationship();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_provenance_ingestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("pointer", models.CharField(max_length=1000)),
                ("text", models.TextField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("char_count", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "parsed_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.parsedsource"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceChunkVisibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("SOURCE_UNAVAILABLE", "Source Unavailable"),
                            ("REVOKED", "Revoked"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="AVAILABLE",
                        max_length=24,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "access_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accesssnapshot"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourcechunk"
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourcelocation"
                    ),
                ),
                (
                    "source_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourceobservation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("OWNED_BY", "Owned By"),
                            ("MAINTAINED_BY", "Maintained By"),
                            ("DEPENDS_ON", "Depends On"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_entity_type",
                    models.CharField(
                        choices=[
                            ("TEAM", "Team"),
                            ("REPOSITORY", "Repository"),
                            ("SERVICE", "Service"),
                            ("COMPONENT", "Component"),
                            ("API", "Api"),
                            ("DATA_ASSET", "Data Asset"),
                            ("DECISION", "Decision"),
                            ("POLICY", "Policy"),
                            ("REQUIREMENT", "Requirement"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_entity_type",
                    models.CharField(
                        choices=[
                            ("TEAM", "Team"),
                            ("REPOSITORY", "Repository"),
                            ("SERVICE", "Service"),
                            ("COMPONENT", "Component"),
                            ("API", "Api"),
                            ("DATA_ASSET", "Data Asset"),
                            ("DECISION", "Decision"),
                            ("POLICY", "Policy"),
                            ("REQUIREMENT", "Requirement"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "extraction_class",
                    models.CharField(
                        choices=[
                            ("MECHANICAL", "Mechanical"),
                            ("INTERPRETIVE", "Interpretive"),
                            ("HUMAN", "Human"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("observed_at", models.DateTimeField()),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("UNREVIEWED", "Unreviewed"),
                            ("AMBIGUOUS", "Ambiguous"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="UNREVIEWED",
                        max_length=24,
                    ),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "access_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accesssnapshot"
                    ),
                ),
                (
                    "assertion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeassertion"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relationships",
                        to="core.knowledgeentity",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourcelocation"
                    ),
                ),
                (
                    "source_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourceobservation"
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relationships",
                        to="core.knowledgeentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "access_scope", "relationship_type"],
                        name="core_rel_scope_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "assertion",
                            "source_entity",
                            "target_entity",
                            "relationship_type",
                        ),
                        name="core_relationship_assertion_edge_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="core_relationship_org_id_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_entity", models.F("target_entity")), _negated=True
                        ),
                        name="core_relationship_distinct_endpoints",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                        name="core_relationship_confidence_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcechunk",
            constraint=models.UniqueConstraint(
                fields=("organization", "parsed_source", "chunk_index"),
                name="core_source_chunk_index_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunk",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_source_chunk_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_source_chunk_hash_sha256",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcechunkvisibility",
            index=models.Index(
                fields=["organization", "access_scope", "state"], name="core_chunk_vis_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunkvisibility",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_chunk", "source_observation"),
                name="core_chunk_visibility_observation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunkvisibility",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_chunk_visibility_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunkvisibility",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", True), ("state", "AVAILABLE")),
                    models.Q(
                        ("revoked_at__isnull", False),
                        ("state__in", ["SOURCE_UNAVAILABLE", "REVOKED", "EXCLUDED"]),
                    ),
                    _connector="OR",
                ),
                name="core_chunk_visibility_state_coherent",
            ),
        ),
        migrations.RunSQL(sql=SAME_TENANT_SQL, reverse_sql=DROP_SAME_TENANT_SQL),
        migrations.RunSQL(sql=CHUNK_TRIGGER_SQL, reverse_sql=DROP_CHUNK_TRIGGER_SQL),
        migrations.RunSQL(
            sql=VISIBILITY_TRIGGER_SQL,
            reverse_sql=DROP_VISIBILITY_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=RELATIONSHIP_TRIGGER_SQL,
            reverse_sql=DROP_RELATIONSHIP_TRIGGER_SQL,
        ),
    ]
