# Generated by Django 5.2.5 on 2026-07-28 09:45

import uuid
from typing import ClassVar

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
from pgvector.django import VectorExtension

SAME_TENANT_RELATIONSHIPS = (
    (
        "core_sourcechunksearchindex",
        "source_chunk_id",
        "core_sourcechunk",
        "chunksearch_chunk_tenant_fk",
    ),
    (
        "core_retrievalwatermark",
        "repository_id",
        "core_repository",
        "watermark_repo_tenant_fk",
    ),
    (
        "core_contextpacketrecord",
        "artifact_id",
        "core_immutableartifact",
        "packet_artifact_tenant_fk",
    ),
    (
        "core_contextpacketrecord",
        "repository_id",
        "core_repository",
        "packet_repo_tenant_fk",
    ),
    (
        "core_contextpacketrecord",
        "access_scope_id",
        "core_accessscope",
        "packet_scope_tenant_fk",
    ),
    (
        "core_contextpacketitem",
        "context_packet_id",
        "core_contextpacketrecord",
        "packetitem_packet_tenant_fk",
    ),
    (
        "core_contextpacketitem",
        "source_assertion_id",
        "core_knowledgeassertion",
        "packetitem_assert_tenant_fk",
    ),
    (
        "core_contextpacketitem",
        "source_relationship_id",
        "core_knowledgerelationship",
        "packetitem_rel_tenant_fk",
    ),
    (
        "core_contextpacketitem",
        "source_chunk_id",
        "core_sourcechunk",
        "packetitem_chunk_tenant_fk",
    ),
    (
        "core_contextpacketitem",
        "source_conflict_id",
        "core_assertionconflict",
        "packetitem_conflict_tenant_fk",
    ),
    (
        "core_contextpacketcitation",
        "context_packet_id",
        "core_contextpacketrecord",
        "citation_packet_tenant_fk",
    ),
    (
        "core_contextpacketcitation",
        "context_item_id",
        "core_contextpacketitem",
        "citation_item_tenant_fk",
    ),
    (
        "core_contextpacketcitation",
        "source_location_id",
        "core_sourcelocation",
        "citation_location_tenant_fk",
    ),
    (
        "core_contextpacketcitation",
        "source_observation_id",
        "core_sourceobservation",
        "citation_observation_tenant_fk",
    ),
    (
        "core_contextpacketcitation",
        "access_snapshot_id",
        "core_accesssnapshot",
        "citation_snapshot_tenant_fk",
    ),
    (
        "core_contextpacketinvalidation",
        "context_packet_id",
        "core_contextpacketrecord",
        "invalidation_packet_tenant_fk",
    ),
    (
        "core_contextpacketinvalidation",
        "repository_id",
        "core_repository",
        "invalidation_repo_tenant_fk",
    ),
)
SAME_TENANT_SQL = "\n".join(
    (
        f"ALTER TABLE {table} ADD CONSTRAINT {name} "
        f"FOREIGN KEY (organization_id, {column}) "
        f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    )
    for table, column, target, name in SAME_TENANT_RELATIONSHIPS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name};"
    for table, _column, _target, name in reversed(SAME_TENANT_RELATIONSHIPS)
)

RETRIEVAL_TRIGGER_SQL = """
CREATE FUNCTION core_reject_retrieval_immutable_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is immutable', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION core_validate_chunk_search_index() RETURNS trigger AS $$
DECLARE
    chunk_text text;
    chunk_hash text;
BEGIN
    SELECT text, content_hash INTO chunk_text, chunk_hash
      FROM core_sourcechunk
     WHERE id = NEW.source_chunk_id
       AND organization_id = NEW.organization_id;
    IF chunk_hash IS NULL OR NEW.indexed_text_hash <> chunk_hash THEN
        RAISE EXCEPTION 'chunk search index identity is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    NEW.search_vector := to_tsvector('simple', chunk_text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION core_validate_context_packet() RETURNS trigger AS $$
DECLARE
    artifact_kind text;
    artifact_scope uuid;
BEGIN
    SELECT kind, access_scope_id INTO artifact_kind, artifact_scope
      FROM core_immutableartifact
     WHERE id = NEW.artifact_id
       AND organization_id = NEW.organization_id;
    IF artifact_kind IS NULL
       OR artifact_kind <> 'CONTEXT_PACKET'
       OR artifact_scope IS DISTINCT FROM NEW.access_scope_id THEN
        RAISE EXCEPTION 'context packet artifact identity is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM core_accessscope
         WHERE id = NEW.access_scope_id
           AND organization_id = NEW.organization_id
           AND is_active
           AND is_derived
           AND boundary_sealed_at IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'context packet scope must be an active sealed intersection'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION core_validate_context_packet_item() RETURNS trigger AS $$
BEGIN
    IF NEW.content_hash <> core_ingestion_jsonb_sha256(NEW.payload) THEN
        RAISE EXCEPTION 'context packet item hash does not match payload'
            USING ERRCODE = '23514';
    END IF;
    IF (
        NEW.kind IN ('POLICY', 'ASSERTION', 'DECISION', 'INCIDENT')
        AND NEW.source_assertion_id IS NULL
    ) OR (
        NEW.kind = 'RELATIONSHIP' AND NEW.source_relationship_id IS NULL
    ) OR (
        NEW.kind = 'SOURCE_EXCERPT' AND NEW.source_chunk_id IS NULL
    ) OR (
        NEW.kind = 'CONFLICT' AND NEW.source_conflict_id IS NULL
    ) THEN
        RAISE EXCEPTION 'context packet item source type is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION core_validate_context_packet_citation() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM core_contextpacketitem item
         WHERE item.id = NEW.context_item_id
           AND item.organization_id = NEW.organization_id
           AND item.context_packet_id = NEW.context_packet_id
    ) THEN
        RAISE EXCEPTION 'context packet citation item is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_location_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM core_sourcelocation location
          JOIN core_sourceobservation observation
            ON observation.id = location.source_observation_id
           AND observation.organization_id = location.organization_id
         WHERE location.id = NEW.source_location_id
           AND location.organization_id = NEW.organization_id
           AND observation.id = NEW.source_observation_id
           AND observation.access_snapshot_id = NEW.access_snapshot_id
    ) THEN
        RAISE EXCEPTION 'context packet citation provenance is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION core_validate_context_packet_invalidation() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM core_contextpacketrecord packet
         WHERE packet.id = NEW.context_packet_id
           AND packet.organization_id = NEW.organization_id
           AND packet.repository_id = NEW.repository_id
    ) THEN
        RAISE EXCEPTION 'context packet invalidation target is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER chunksearch_validate
BEFORE INSERT ON core_sourcechunksearchindex
FOR EACH ROW EXECUTE FUNCTION core_validate_chunk_search_index();
CREATE TRIGGER packet_validate
BEFORE INSERT ON core_contextpacketrecord
FOR EACH ROW EXECUTE FUNCTION core_validate_context_packet();
CREATE TRIGGER packetitem_validate
BEFORE INSERT ON core_contextpacketitem
FOR EACH ROW EXECUTE FUNCTION core_validate_context_packet_item();
CREATE TRIGGER packetcitation_validate
BEFORE INSERT ON core_contextpacketcitation
FOR EACH ROW EXECUTE FUNCTION core_validate_context_packet_citation();
CREATE TRIGGER packetinvalidation_validate
BEFORE INSERT ON core_contextpacketinvalidation
FOR EACH ROW EXECUTE FUNCTION core_validate_context_packet_invalidation();

CREATE TRIGGER chunksearch_immutable
BEFORE UPDATE OR DELETE ON core_sourcechunksearchindex
FOR EACH ROW EXECUTE FUNCTION core_reject_retrieval_immutable_change();
CREATE TRIGGER packet_immutable
BEFORE UPDATE OR DELETE ON core_contextpacketrecord
FOR EACH ROW EXECUTE FUNCTION core_reject_retrieval_immutable_change();
CREATE TRIGGER packetitem_immutable
BEFORE UPDATE OR DELETE ON core_contextpacketitem
FOR EACH ROW EXECUTE FUNCTION core_reject_retrieval_immutable_change();
CREATE TRIGGER packetcitation_immutable
BEFORE UPDATE OR DELETE ON core_contextpacketcitation
FOR EACH ROW EXECUTE FUNCTION core_reject_retrieval_immutable_change();
CREATE TRIGGER packetinvalidation_immutable
BEFORE UPDATE OR DELETE ON core_contextpacketinvalidation
FOR EACH ROW EXECUTE FUNCTION core_reject_retrieval_immutable_change();
"""

DROP_RETRIEVAL_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS packetinvalidation_immutable ON core_contextpacketinvalidation;
DROP TRIGGER IF EXISTS packetcitation_immutable ON core_contextpacketcitation;
DROP TRIGGER IF EXISTS packetitem_immutable ON core_contextpacketitem;
DROP TRIGGER IF EXISTS packet_immutable ON core_contextpacketrecord;
DROP TRIGGER IF EXISTS chunksearch_immutable ON core_sourcechunksearchindex;
DROP TRIGGER IF EXISTS packetinvalidation_validate ON core_contextpacketinvalidation;
DROP TRIGGER IF EXISTS packetcitation_validate ON core_contextpacketcitation;
DROP TRIGGER IF EXISTS packetitem_validate ON core_contextpacketitem;
DROP TRIGGER IF EXISTS packet_validate ON core_contextpacketrecord;
DROP TRIGGER IF EXISTS chunksearch_validate ON core_sourcechunksearchindex;
DROP FUNCTION IF EXISTS core_validate_context_packet_invalidation();
DROP FUNCTION IF EXISTS core_validate_context_packet_citation();
DROP FUNCTION IF EXISTS core_validate_context_packet_item();
DROP FUNCTION IF EXISTS core_validate_context_packet();
DROP FUNCTION IF EXISTS core_validate_chunk_search_index();
DROP FUNCTION IF EXISTS core_reject_retrieval_immutable_change();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0005_verify_ingestion_digests"),
    ]

    operations: ClassVar = [
        TrigramExtension(),
        VectorExtension(),
        migrations.CreateModel(
            name="ContextPacketRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("PREPARE", "Prepare"),
                            ("BUILD", "Build"),
                            ("PREFLIGHT", "Preflight"),
                            ("ASSURANCE", "Assurance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("normalized_request", models.JSONField()),
                ("request_hash", models.CharField(max_length=64)),
                ("authorization_hash", models.CharField(max_length=64)),
                ("selection_hash", models.CharField(max_length=64)),
                ("retrieval_watermark", models.PositiveBigIntegerField()),
                ("retrieval_algorithm_version", models.CharField(max_length=50)),
                ("index_version", models.CharField(max_length=50)),
                ("embedding_version", models.CharField(max_length=50)),
                ("budget_max_items", models.PositiveIntegerField()),
                ("budget_max_tokens", models.PositiveIntegerField()),
                ("budget_max_bytes", models.PositiveIntegerField()),
                ("budget_max_citations", models.PositiveIntegerField()),
                ("selected_items", models.PositiveIntegerField()),
                ("selected_tokens", models.PositiveIntegerField()),
                ("selected_bytes", models.PositiveIntegerField()),
                ("selected_citations", models.PositiveIntegerField()),
                ("limitations", models.JSONField(default=list)),
                ("cache_key", models.CharField(max_length=64)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.immutableartifact"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextPacketItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("POLICY", "Policy"),
                            ("RELATIONSHIP", "Relationship"),
                            ("ASSERTION", "Assertion"),
                            ("SOURCE_EXCERPT", "Source Excerpt"),
                            ("DECISION", "Decision"),
                            ("INCIDENT", "Incident"),
                            ("CONFLICT", "Conflict"),
                        ],
                        max_length=24,
                    ),
                ),
                ("item_key", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                (
                    "freshness",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("STALE", "Stale"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_inferred", models.BooleanField(default=False)),
                ("selection_reason", models.CharField(max_length=500)),
                ("rank_score", models.FloatField()),
                ("token_count", models.PositiveIntegerField()),
                ("byte_count", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_assertion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.knowledgeassertion",
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sourcechunk",
                    ),
                ),
                (
                    "source_conflict",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.assertionconflict",
                    ),
                ),
                (
                    "source_relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.knowledgerelationship",
                    ),
                ),
                (
                    "context_packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.contextpacketrecord"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextPacketInvalidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("INGESTION", "Ingestion"),
                            ("CORRECTION", "Correction"),
                            ("REVOCATION", "Revocation"),
                            ("SCOPE_CHANGE", "Scope Change"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=24,
                    ),
                ),
                ("watermark", models.PositiveBigIntegerField()),
                ("details", models.JSONField(default=dict)),
                (
                    "invalidated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
                (
                    "context_packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.contextpacketrecord"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextPacketCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("canonical_url", models.CharField(max_length=1500)),
                ("locator", models.CharField(max_length=1000)),
                ("source_content_hash", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                (
                    "access_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.accesssnapshot",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sourcelocation",
                    ),
                ),
                (
                    "source_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sourceobservation",
                    ),
                ),
                (
                    "context_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.contextpacketitem"
                    ),
                ),
                (
                    "context_packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.contextpacketrecord"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetrievalWatermark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("value", models.PositiveBigIntegerField(default=1)),
                ("reason", models.CharField(default="INITIAL", max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceChunkSearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("index_version", models.CharField(max_length=50)),
                ("embedding_provider", models.CharField(max_length=100)),
                ("embedding_version", models.CharField(max_length=50)),
                ("indexed_text_hash", models.CharField(max_length=64)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=32)),
                (
                    "indexed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.sourcechunk"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contextpacketrecord",
            index=models.Index(
                fields=["organization", "repository", "cache_key"],
                name="core_packet_cache_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "cache_key"), name="core_context_packet_cache_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_context_packet_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[a-f0-9]{64}$")),
                name="core_context_packet_request_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("authorization_hash__regex", "^[a-f0-9]{64}$")),
                name="core_context_packet_auth_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("selection_hash__regex", "^[a-f0-9]{64}$")),
                name="core_context_packet_selection_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("cache_key__regex", "^[a-f0-9]{64}$")),
                name="core_context_packet_cache_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("selected_items__lte", models.F("budget_max_items")),
                    ("selected_tokens__lte", models.F("budget_max_tokens")),
                    ("selected_bytes__lte", models.F("budget_max_bytes")),
                    ("selected_citations__lte", models.F("budget_max_citations")),
                ),
                name="core_context_packet_budget_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "context_packet", "position"),
                name="core_context_packet_item_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "context_packet", "item_key"),
                name="core_context_packet_item_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_context_packet_item_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_context_packet_item_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank_score__gte", 0.0)),
                name="core_context_packet_item_score_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketinvalidation",
            constraint=models.UniqueConstraint(
                fields=("organization", "context_packet", "watermark", "reason"),
                name="core_context_packet_invalidation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketinvalidation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_context_packet_inval_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketcitation",
            constraint=models.UniqueConstraint(
                fields=("organization", "context_packet", "context_item", "position"),
                name="core_context_packet_citation_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketcitation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_context_packet_citation_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contextpacketcitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_context_packet_citation_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalwatermark",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="core_retrievalwatermark_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalwatermark",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository"), name="core_retrieval_watermark_repo_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalwatermark",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_retrieval_watermark_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalwatermark",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 1)), name="core_retrieval_watermark_value_gte_1"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcechunksearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="core_chunk_search_fts_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcechunksearchindex",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="core_chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunksearchindex",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_chunk", "index_version", "embedding_version"),
                name="core_chunk_search_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunksearchindex",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_chunk_search_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunksearchindex",
            constraint=models.CheckConstraint(
                condition=models.Q(("indexed_text_hash__regex", "^[a-f0-9]{64}$")),
                name="core_chunk_search_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="assertionconflict",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="core_assertion_conflict_org_id_unique",
            ),
        ),
        migrations.RunSQL(
            sql=SAME_TENANT_SQL,
            reverse_sql=DROP_SAME_TENANT_SQL,
        ),
        migrations.RunSQL(
            sql=RETRIEVAL_TRIGGER_SQL,
            reverse_sql=DROP_RETRIEVAL_TRIGGER_SQL,
        ),
    ]
