# Generated by Django 5.2.5 on 2026-07-28 12:37

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONS = (
    ("core_approval", "repository_id", "core_repository"),
    ("core_approval", "work_item_revision_id", "core_workitemrevision"),
    ("core_evidencemanifest", "repository_id", "core_repository"),
    ("core_evidencemanifest", "access_scope_id", "core_accessscope"),
    ("core_evidencemanifest", "artifact_id", "core_immutableartifact"),
    ("core_evidencemanifest", "work_item_revision_id", "core_workitemrevision"),
    ("core_evidence", "manifest_id", "core_evidencemanifest"),
    ("core_evidence", "approval_id", "core_approval"),
    ("core_evidenceretentionevent", "evidence_id", "core_evidence"),
    ("core_policy", "access_scope_id", "core_accessscope"),
    ("core_policyevaluation", "repository_id", "core_repository"),
    ("core_policyevaluation", "access_scope_id", "core_accessscope"),
    ("core_policyevaluation", "work_item_revision_id", "core_workitemrevision"),
    ("core_policyversion", "policy_id", "core_policy"),
    ("core_policyrequirement", "policy_version_id", "core_policyversion"),
    ("core_policyoverride", "policy_evaluation_id", "core_policyevaluation"),
    ("core_policyoverride", "policy_version_id", "core_policyversion"),
    ("core_policyoverride", "repository_id", "core_repository"),
    ("core_policybinding", "policy_version_id", "core_policyversion"),
    ("core_workitem", "repository_id", "core_repository"),
    ("core_workitem", "access_scope_id", "core_accessscope"),
    ("core_workitemrevision", "work_item_id", "core_workitem"),
    ("core_requirement", "work_item_revision_id", "core_workitemrevision"),
    ("core_nonrequirement", "work_item_revision_id", "core_workitemrevision"),
    ("core_assumption", "work_item_revision_id", "core_workitemrevision"),
    ("core_acceptancecriterion", "work_item_revision_id", "core_workitemrevision"),
    ("core_acceptancecriterion", "requirement_id", "core_requirement"),
    ("core_decision", "work_item_revision_id", "core_workitemrevision"),
    ("core_worksummary", "work_item_revision_id", "core_workitemrevision"),
    ("core_criterionevidence", "access_scope_id", "core_accessscope"),
    ("core_criterionevidence", "criterion_id", "core_acceptancecriterion"),
    ("core_criterionevidence", "evidence_id", "core_evidence"),
)


def _same_tenant_constraint_name(table: str, column: str) -> str:
    return f"{table.removeprefix('core_')}_{column.removesuffix('_id')}_tenant_fk"


SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} ADD CONSTRAINT {_same_tenant_constraint_name(table, column)} "
    f"FOREIGN KEY (organization_id, {column}) "
    f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    for table, column, target in SAME_TENANT_RELATIONS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {_same_tenant_constraint_name(table, column)};"
    for table, column, _target in reversed(SAME_TENANT_RELATIONS)
)

IMMUTABLE_TABLES = (
    "core_workitemrevision",
    "core_requirement",
    "core_nonrequirement",
    "core_assumption",
    "core_acceptancecriterion",
    "core_decision",
    "core_approval",
    "core_worksummary",
    "core_policyversion",
    "core_policybinding",
    "core_policyrequirement",
    "core_policyevaluation",
    "core_policyoverride",
    "core_evidencemanifest",
    "core_evidence",
    "core_evidenceretentionevent",
    "core_criterionevidence",
)
IMMUTABILITY_SQL = """
CREATE FUNCTION core_reject_governance_immutable_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is immutable', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
""" + "\n".join(
    f"""
CREATE TRIGGER {table.removeprefix("core_")}_immutable
BEFORE UPDATE OR DELETE ON {table}
FOR EACH ROW EXECUTE FUNCTION core_reject_governance_immutable_change();
"""
    for table in IMMUTABLE_TABLES
)
DROP_IMMUTABILITY_SQL = (
    "\n".join(
        f"DROP TRIGGER IF EXISTS {table.removeprefix('core_')}_immutable ON {table};"
        for table in reversed(IMMUTABLE_TABLES)
    )
    + "\nDROP FUNCTION IF EXISTS core_reject_governance_immutable_change();"
)

VALIDATION_SQL = """
CREATE FUNCTION core_validate_work_policy_pointer() RETURNS trigger AS $$
BEGIN
    IF TG_TABLE_NAME = 'core_workitem' AND NOT EXISTS (
        SELECT 1 FROM core_workitemrevision revision
        WHERE revision.organization_id = NEW.organization_id
          AND revision.work_item_id = NEW.id
          AND revision.revision = NEW.revision
          AND revision.content_hash = NEW.current_content_hash
    ) THEN
        RAISE EXCEPTION 'work item current revision pointer is invalid' USING ERRCODE = '23514';
    END IF;
    IF TG_TABLE_NAME = 'core_policy' AND NOT EXISTS (
        SELECT 1 FROM core_policyversion version
        WHERE version.organization_id = NEW.organization_id
          AND version.policy_id = NEW.id
          AND version.version = NEW.revision
          AND version.content_hash = NEW.current_content_hash
    ) THEN
        RAISE EXCEPTION 'policy current version pointer is invalid' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER workitem_current_pointer
AFTER INSERT OR UPDATE ON core_workitem
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_work_policy_pointer();
CREATE CONSTRAINT TRIGGER policy_current_pointer
AFTER INSERT OR UPDATE ON core_policy
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_work_policy_pointer();

CREATE FUNCTION core_validate_governance_binding() RETURNS trigger AS $$
DECLARE
    manifest_row core_evidencemanifest%ROWTYPE;
    criterion_revision_id uuid;
BEGIN
    IF TG_TABLE_NAME = 'core_acceptancecriterion' THEN
        IF NEW.requirement_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM core_requirement requirement
            WHERE requirement.id = NEW.requirement_id
              AND requirement.organization_id = NEW.organization_id
              AND requirement.work_item_revision_id = NEW.work_item_revision_id
        ) THEN
            RAISE EXCEPTION 'criterion requirement binding is invalid'
            USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'core_approval' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM core_workitemrevision revision
            JOIN core_workitem item ON item.id = revision.work_item_id
            WHERE revision.id = NEW.work_item_revision_id
              AND revision.organization_id = NEW.organization_id
              AND item.repository_id = NEW.repository_id
        ) THEN
            RAISE EXCEPTION 'approval target binding is invalid' USING ERRCODE = '23514';
        END IF;
        IF NOT (
            (
                NEW.target_kind = 'WORK_ITEM_REVISION'
                AND NEW.target_key = NEW.work_item_revision_id::text
            )
            OR (
                NEW.target_kind = 'REQUIREMENT'
                AND EXISTS (
                    SELECT 1 FROM core_requirement requirement
                    WHERE requirement.work_item_revision_id = NEW.work_item_revision_id
                      AND requirement.organization_id = NEW.organization_id
                      AND requirement.code = NEW.target_key
                )
            )
            OR (
                NEW.target_kind = 'ACCEPTANCE_CRITERION'
                AND EXISTS (
                    SELECT 1 FROM core_acceptancecriterion criterion
                    WHERE criterion.work_item_revision_id = NEW.work_item_revision_id
                      AND criterion.organization_id = NEW.organization_id
                      AND criterion.code = NEW.target_key
                )
            )
            OR (
                NEW.target_kind = 'DECISION'
                AND EXISTS (
                    SELECT 1 FROM core_decision decision
                    WHERE decision.work_item_revision_id = NEW.work_item_revision_id
                      AND decision.organization_id = NEW.organization_id
                      AND decision.code = NEW.target_key
                )
            )
        ) THEN
            RAISE EXCEPTION 'approval semantic target is invalid' USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'core_evidencemanifest' THEN
        IF NOT EXISTS (
            SELECT 1 FROM core_immutableartifact artifact
            WHERE artifact.id = NEW.artifact_id
              AND artifact.organization_id = NEW.organization_id
              AND artifact.access_scope_id = NEW.access_scope_id
              AND artifact.kind = 'EVIDENCE_MANIFEST'
              AND artifact.content_hash = NEW.payload_hash
        ) THEN
            RAISE EXCEPTION 'manifest artifact binding is invalid' USING ERRCODE = '23514';
        END IF;
        IF NEW.work_item_revision_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM core_workitemrevision revision
            JOIN core_workitem item ON item.id = revision.work_item_id
            WHERE revision.id = NEW.work_item_revision_id
              AND revision.organization_id = NEW.organization_id
              AND item.repository_id = NEW.repository_id
              AND item.access_scope_id = NEW.access_scope_id
        ) THEN
            RAISE EXCEPTION 'manifest work binding is invalid' USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'core_evidence' THEN
        SELECT * INTO manifest_row
        FROM core_evidencemanifest
        WHERE id = NEW.manifest_id AND organization_id = NEW.organization_id;
        IF NOT FOUND OR manifest_row.commit_sha <> NEW.commit_sha THEN
            RAISE EXCEPTION 'evidence commit binding is invalid' USING ERRCODE = '23514';
        END IF;
        IF NEW.kind = 'MANUAL_APPROVAL' AND NOT EXISTS (
            SELECT 1 FROM core_approval approval
            WHERE approval.id = NEW.approval_id
              AND approval.organization_id = NEW.organization_id
              AND approval.work_item_revision_id = manifest_row.work_item_revision_id
              AND approval.repository_id = manifest_row.repository_id
              AND approval.status = 'APPROVED'
              AND (
                  (
                      approval.target_kind = 'WORK_ITEM_REVISION'
                      AND approval.target_key = manifest_row.work_item_revision_id::text
                  )
                  OR (
                      approval.target_kind = 'ACCEPTANCE_CRITERION'
                      AND NEW.criterion_codes ? approval.target_key
                  )
                  OR (
                      approval.target_kind = 'REQUIREMENT'
                      AND EXISTS (
                          SELECT 1
                          FROM core_acceptancecriterion criterion
                          JOIN core_requirement requirement
                            ON requirement.id = criterion.requirement_id
                           AND requirement.organization_id = criterion.organization_id
                          WHERE criterion.work_item_revision_id =
                                manifest_row.work_item_revision_id
                            AND criterion.organization_id = NEW.organization_id
                            AND NEW.criterion_codes ? criterion.code
                            AND requirement.code = approval.target_key
                      )
                  )
              )
        ) THEN
            RAISE EXCEPTION 'manual evidence approval binding is invalid' USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'core_criterionevidence' THEN
        SELECT work_item_revision_id INTO criterion_revision_id
        FROM core_acceptancecriterion
        WHERE id = NEW.criterion_id AND organization_id = NEW.organization_id;
        IF NOT EXISTS (
            SELECT 1
            FROM core_workitemrevision revision
            JOIN core_workitem item ON item.id = revision.work_item_id
            WHERE revision.id = criterion_revision_id
              AND revision.organization_id = NEW.organization_id
              AND item.access_scope_id = NEW.access_scope_id
        ) THEN
            RAISE EXCEPTION 'criterion mapping scope is invalid' USING ERRCODE = '23514';
        END IF;
        IF NEW.evidence_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM core_evidence evidence
            JOIN core_evidencemanifest manifest ON manifest.id = evidence.manifest_id
            WHERE evidence.id = NEW.evidence_id
              AND evidence.organization_id = NEW.organization_id
              AND evidence.commit_sha = NEW.target_commit
              AND manifest.work_item_revision_id = criterion_revision_id
              AND manifest.access_scope_id = NEW.access_scope_id
              AND manifest.pull_request_number = NEW.pull_request_number
        ) THEN
            RAISE EXCEPTION 'criterion evidence binding is invalid' USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'core_policyoverride' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM core_policyevaluation evaluation
            JOIN core_policyversion version
              ON version.id = NEW.policy_version_id
             AND version.organization_id = NEW.organization_id
            JOIN core_policy policy
              ON policy.id = version.policy_id
             AND policy.organization_id = NEW.organization_id
            JOIN core_policyrequirement requirement
              ON requirement.policy_version_id = version.id
             AND requirement.organization_id = NEW.organization_id
             AND requirement.code = NEW.requirement_code
            WHERE evaluation.id = NEW.policy_evaluation_id
              AND evaluation.organization_id = NEW.organization_id
              AND evaluation.repository_id = NEW.repository_id
              AND evaluation.pull_request_number = NEW.pull_request_number
              AND evaluation.commit_sha = NEW.commit_sha
              AND evaluation.access_scope_id = policy.access_scope_id
              AND evaluation.input_payload->'policy_versions' @>
                  jsonb_build_array(jsonb_build_object('id', NEW.policy_version_id::text))
        ) THEN
            RAISE EXCEPTION 'policy override binding is invalid' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER approval_binding
AFTER INSERT ON core_approval DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_governance_binding();
CREATE CONSTRAINT TRIGGER criterion_requirement_binding
AFTER INSERT ON core_acceptancecriterion DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_governance_binding();
CREATE CONSTRAINT TRIGGER evidencemanifest_binding
AFTER INSERT ON core_evidencemanifest DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_governance_binding();
CREATE CONSTRAINT TRIGGER evidence_binding
AFTER INSERT ON core_evidence DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_governance_binding();
CREATE CONSTRAINT TRIGGER criterionevidence_binding
AFTER INSERT ON core_criterionevidence DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_governance_binding();
CREATE CONSTRAINT TRIGGER policyoverride_binding
AFTER INSERT ON core_policyoverride DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_governance_binding();
"""
DROP_VALIDATION_SQL = """
DROP TRIGGER IF EXISTS policyoverride_binding ON core_policyoverride;
DROP TRIGGER IF EXISTS criterionevidence_binding ON core_criterionevidence;
DROP TRIGGER IF EXISTS evidence_binding ON core_evidence;
DROP TRIGGER IF EXISTS evidencemanifest_binding ON core_evidencemanifest;
DROP TRIGGER IF EXISTS approval_binding ON core_approval;
DROP TRIGGER IF EXISTS criterion_requirement_binding ON core_acceptancecriterion;
DROP FUNCTION IF EXISTS core_validate_governance_binding();
DROP TRIGGER IF EXISTS policy_current_pointer ON core_policy;
DROP TRIGGER IF EXISTS workitem_current_pointer ON core_workitem;
DROP FUNCTION IF EXISTS core_validate_work_policy_pointer();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0007_packet_item_scope_intersection"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_kind", models.CharField(max_length=40)),
                ("target_key", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")], max_length=16
                    ),
                ),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("authority_action", models.CharField(max_length=100)),
                ("reason", models.CharField(max_length=2000)),
                ("idempotency_key", models.CharField(max_length=64)),
                (
                    "decided_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pull_request_number", models.PositiveIntegerField()),
                ("commit_sha", models.CharField(max_length=40)),
                ("schema_version", models.CharField(max_length=20)),
                ("producer", models.CharField(max_length=200)),
                ("producer_version", models.CharField(max_length=100)),
                (
                    "producer_mode",
                    models.CharField(choices=[("MANUAL", "Manual"), ("CI", "Ci")], max_length=16),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload_size", models.PositiveIntegerField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.immutableartifact"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("commit_sha", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CHECK_STATUS", "Check Status"),
                            ("TEST_RESULT", "Test Result"),
                            ("BUILD_RESULT", "Build Result"),
                            ("TYPECHECK_RESULT", "Typecheck Result"),
                            ("LINT_RESULT", "Lint Result"),
                            ("SCREENSHOT", "Screenshot"),
                            ("VIDEO", "Video"),
                            ("CONSOLE_LOG", "Console Log"),
                            ("NETWORK_TRACE", "Network Trace"),
                            ("API_ASSERTION", "Api Assertion"),
                            ("STATIC_ANALYSIS", "Static Analysis"),
                            ("SECURITY_SCAN", "Security Scan"),
                            ("DEPENDENCY_SCAN", "Dependency Scan"),
                            ("MIGRATION_RESULT", "Migration Result"),
                            ("PERFORMANCE_RESULT", "Performance Result"),
                            ("ACCESSIBILITY_RESULT", "Accessibility Result"),
                            ("MANUAL_APPROVAL", "Manual Approval"),
                            ("SOURCE_REFERENCE", "Source Reference"),
                            ("DIFF_REFERENCE", "Diff Reference"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("producer", models.CharField(max_length=200)),
                ("producer_version", models.CharField(max_length=100)),
                ("command", models.CharField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField()),
                ("artifact_reference", models.CharField(blank=True, max_length=2000)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                ("content_hash", models.CharField(max_length=64)),
                ("limitations", models.JSONField(default=list)),
                ("criterion_codes", models.JSONField(default=list)),
                ("retention_class", models.CharField(max_length=100)),
                ("retention_expires_at", models.DateTimeField(blank=True, null=True)),
                ("environment", models.CharField(blank=True, max_length=200)),
                ("scenario", models.CharField(blank=True, max_length=500)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.approval",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.evidencemanifest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceRetentionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.evidence"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("name", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("current_content_hash", models.CharField(max_length=64)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pull_request_number", models.PositiveIntegerField()),
                ("commit_sha", models.CharField(max_length=40)),
                ("reference_time", models.DateTimeField()),
                ("is_simulation", models.BooleanField(default=False)),
                ("input_payload", models.JSONField()),
                ("input_hash", models.CharField(max_length=64)),
                ("output_payload", models.JSONField()),
                ("output_hash", models.CharField(max_length=64)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("schema_version", models.CharField(max_length=20)),
                ("definition", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("effective_at", models.DateTimeField()),
                ("created_by_type", models.CharField(max_length=20)),
                ("created_by_id", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.policy"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "enforcement",
                    models.CharField(
                        choices=[("BLOCKING", "Blocking"), ("ADVISORY", "Advisory")], max_length=16
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("DETERMINISTIC", "Deterministic"),
                            ("EVIDENCE", "Evidence"),
                            ("MODEL_REVIEW", "Model Review"),
                            ("MANUAL_APPROVAL", "Manual Approval"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required_evidence", models.JSONField(default=list)),
                ("required_reviewers", models.JSONField(default=list)),
                ("required_approval", models.BooleanField(default=False)),
                ("report_sections", models.JSONField(default=list)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.policyversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pull_request_number", models.PositiveIntegerField()),
                ("requirement_code", models.CharField(max_length=64)),
                ("commit_sha", models.CharField(max_length=40)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("authority_path", models.CharField(max_length=1000)),
                ("reason", models.CharField(max_length=2000)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "policy_evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.policyevaluation"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.policyversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope_level",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "Organization"),
                            ("PRODUCT", "Product"),
                            ("SYSTEM", "System"),
                            ("REPOSITORY", "Repository"),
                            ("PATH", "Path"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
                ("repository_ids", models.JSONField(default=list)),
                ("entity_ids", models.JSONField(default=list)),
                ("entity_types", models.JSONField(default=list)),
                ("path_patterns", models.JSONField(default=list)),
                ("work_item_types", models.JSONField(default=list)),
                ("target_branches", models.JSONField(default=list)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "policy_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.policyversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("external_key", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("FEATURE", "Feature"),
                            ("BUG", "Bug"),
                            ("SECURITY", "Security"),
                            ("MIGRATION", "Migration"),
                            ("OPERATIONS", "Operations"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("APPROVED", "Approved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("current_content_hash", models.CharField(max_length=64)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkItemRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("title", models.CharField(max_length=500)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("FEATURE", "Feature"),
                            ("BUG", "Bug"),
                            ("SECURITY", "Security"),
                            ("MIGRATION", "Migration"),
                            ("OPERATIONS", "Operations"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("APPROVED", "Approved"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("origin", models.CharField(max_length=100)),
                ("source_references", models.JSONField(default=list)),
                ("normalized_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("created_by_type", models.CharField(max_length=20)),
                ("created_by_id", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=64)),
                ("normalized_text", models.TextField()),
                ("origin", models.CharField(max_length=100)),
                ("owner", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(max_length=24)),
                ("source_references", models.JSONField(default=list)),
                ("related_entity_ids", models.JSONField(default=list)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="policyevaluation",
            name="work_item_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.workitemrevision",
            ),
        ),
        migrations.CreateModel(
            name="NonRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=64)),
                ("normalized_text", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidencemanifest",
            name="work_item_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.workitemrevision",
            ),
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("outcome", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=64)),
                ("normalized_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("VALIDATED", "Validated"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("validation_reference", models.CharField(blank=True, max_length=1000)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="approval",
            name="work_item_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
            ),
        ),
        migrations.CreateModel(
            name="AcceptanceCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=64)),
                ("normalized_text", models.TextField()),
                ("required_evidence_types", models.JSONField(default=list)),
                ("manual_approval_allowed", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.requirement",
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("summary_type", models.CharField(max_length=40)),
                ("structured_data", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("producer", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workitemrevision"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriterionEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_commit", models.CharField(max_length=40)),
                ("pull_request_number", models.PositiveIntegerField()),
                ("reference_time", models.DateTimeField()),
                ("required_evidence_type", models.CharField(max_length=32)),
                ("engine_version", models.CharField(max_length=64)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "classification",
                    models.CharField(
                        choices=[("DIRECT", "Direct"), ("INDIRECT", "Indirect"), ("GAP", "Gap")],
                        max_length=16,
                    ),
                ),
                (
                    "assessment",
                    models.CharField(
                        choices=[("SATISFIED", "Satisfied"), ("GAP", "Gap")], max_length=16
                    ),
                ),
                ("verifier_type", models.CharField(max_length=20)),
                ("verifier_id", models.CharField(max_length=200)),
                ("limitations", models.JSONField(default=list)),
                ("confidence", models.FloatField()),
                ("gap_code", models.CharField(blank=True, max_length=64)),
                ("gap_description", models.CharField(blank=True, max_length=2000)),
                ("mapping_key", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.acceptancecriterion"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.evidence",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="core_criterion_evidence_org_id_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "mapping_key"),
                        name="core_criterion_evidence_key_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target_commit__regex", "^[a-f0-9]{40}$")),
                        name="core_criterion_evidence_commit_sha",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mapping_key__regex", "^[a-f0-9]{64}$")),
                        name="core_criterion_evidence_key_sha",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("input_hash__regex", "^[a-f0-9]{64}$")),
                        name="core_criterion_evidence_input_sha",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pull_request_number__gte", 1)),
                        name="core_criterion_evidence_pr_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("engine_version", ""), _negated=True),
                            models.Q(("required_evidence_type", ""), _negated=True),
                        ),
                        name="core_criterion_evidence_versions_present",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                        name="core_criterion_evidence_confidence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("assessment", "SATISFIED"),
                                ("evidence__isnull", False),
                                ("gap_code", ""),
                                ("gap_description", ""),
                            ),
                            models.Q(
                                ("assessment", "GAP"),
                                ("evidence__isnull", True),
                                models.Q(("gap_code", ""), _negated=True),
                                models.Q(("gap_description", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="core_criterion_evidence_coherent",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_evidence_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "manifest", "content_hash", "kind", "name"),
                name="core_evidence_manifest_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("commit_sha__regex", "^[a-f0-9]{40}$")),
                name="core_evidence_commit_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_evidence_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_at__isnull", True),
                    ("completed_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="core_evidence_time_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("approval__isnull", False), ("kind", "MANUAL_APPROVAL")),
                    models.Q(
                        models.Q(("kind", "MANUAL_APPROVAL"), _negated=True),
                        ("approval__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="core_evidence_manual_approval_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_evidence_retention_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_policy_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_policy_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_policy_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_policy_version_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "policy", "version"),
                name="core_policy_version_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "policy", "content_hash"),
                name="core_policy_version_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="core_policy_version_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_policy_version_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrequirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_policy_requirement_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrequirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "policy_version", "code"),
                name="core_policy_requirement_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyoverride",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_policy_override_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyoverride",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="core_policy_override_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(("commit_sha__regex", "^[a-f0-9]{40}$")),
                name="core_policy_override_commit_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[a-f0-9]{64}$")),
                name="core_policy_override_key_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="policybinding",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_policy_binding_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="workitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_workitem_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="workitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_work_item_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="workitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_key__isnull", False)),
                fields=("organization", "repository", "external_key"),
                name="core_work_item_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="workitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_work_item_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="workitemrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_work_revision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="workitemrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item", "revision"),
                name="core_work_revision_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="workitemrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item", "content_hash"),
                name="core_work_revision_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="workitemrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_work_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="workitemrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_work_revision_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_requirement_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "code"),
                name="core_requirement_revision_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "position"),
                name="core_requirement_revision_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyevaluation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_policy_evaluation_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyevaluation",
            constraint=models.UniqueConstraint(
                fields=("organization", "input_hash"), name="core_policy_evaluation_input_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("commit_sha__regex", "^[a-f0-9]{40}$")),
                name="core_policy_evaluation_commit_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_hash__regex", "^[a-f0-9]{64}$")),
                name="core_policy_evaluation_input_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_hash__regex", "^[a-f0-9]{64}$")),
                name="core_policy_evaluation_output_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonrequirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_non_requirement_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="nonrequirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "code"),
                name="core_non_requirement_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonrequirement",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "position"),
                name="core_non_requirement_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencemanifest",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_evidence_manifest_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencemanifest",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "payload_hash"),
                name="core_evidence_manifest_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencemanifest",
            constraint=models.CheckConstraint(
                condition=models.Q(("commit_sha__regex", "^[a-f0-9]{40}$")),
                name="core_evidence_manifest_commit_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencemanifest",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_hash__regex", "^[a-f0-9]{64}$")),
                name="core_evidence_manifest_payload_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_decision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "code"),
                name="core_decision_revision_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "position"),
                name="core_decision_revision_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assumption",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_assumption_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assumption",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "code"),
                name="core_assumption_revision_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assumption",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "position"),
                name="core_assumption_revision_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_approval_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="core_approval_idempotency_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[a-f0-9]{64}$")),
                name="core_approval_key_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptancecriterion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_criterion_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptancecriterion",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "code"),
                name="core_criterion_revision_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptancecriterion",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "position"),
                name="core_criterion_revision_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="worksummary",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_work_summary_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="worksummary",
            constraint=models.UniqueConstraint(
                fields=("organization", "work_item_revision", "content_hash"),
                name="core_work_summary_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="worksummary",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_work_summary_hash_sha256",
            ),
        ),
        migrations.RunSQL(
            sql=SAME_TENANT_SQL,
            reverse_sql=DROP_SAME_TENANT_SQL,
        ),
        migrations.RunSQL(
            sql=VALIDATION_SQL,
            reverse_sql=DROP_VALIDATION_SQL,
        ),
        migrations.RunSQL(
            sql=IMMUTABILITY_SQL,
            reverse_sql=DROP_IMMUTABILITY_SQL,
        ),
    ]
