# Generated by Django 5.2.5 on 2026-07-28 12:48

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

REVOCATION_SQL = """
ALTER TABLE core_approvalrevocation
ADD CONSTRAINT approvalrevocation_approval_tenant_fk
FOREIGN KEY (organization_id, approval_id)
REFERENCES core_approval (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE core_policyoverriderevocation
ADD CONSTRAINT policyoverriderevocation_override_tenant_fk
FOREIGN KEY (organization_id, policy_override_id)
REFERENCES core_policyoverride (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;

CREATE TRIGGER approvalrevocation_immutable
BEFORE UPDATE OR DELETE ON core_approvalrevocation
FOR EACH ROW EXECUTE FUNCTION core_reject_governance_immutable_change();
CREATE TRIGGER policyoverriderevocation_immutable
BEFORE UPDATE OR DELETE ON core_policyoverriderevocation
FOR EACH ROW EXECUTE FUNCTION core_reject_governance_immutable_change();

CREATE FUNCTION core_validate_unrevoked_manual_evidence() RETURNS trigger AS $$
DECLARE
    approval_id_value uuid;
BEGIN
    IF TG_TABLE_NAME = 'core_evidence' THEN
        approval_id_value := NEW.approval_id;
        IF approval_id_value IS NOT NULL AND EXISTS (
            SELECT 1 FROM core_approvalrevocation revocation
            WHERE revocation.organization_id = NEW.organization_id
              AND revocation.approval_id = approval_id_value
        ) THEN
            RAISE EXCEPTION 'revoked approval cannot satisfy evidence'
            USING ERRCODE = '23514';
        END IF;
    ELSE
        SELECT evidence.approval_id INTO approval_id_value
        FROM core_evidence evidence
        WHERE evidence.id = NEW.evidence_id
          AND evidence.organization_id = NEW.organization_id
          AND evidence.kind = 'MANUAL_APPROVAL';
        IF approval_id_value IS NOT NULL AND EXISTS (
            SELECT 1 FROM core_approvalrevocation revocation
            WHERE revocation.organization_id = NEW.organization_id
              AND revocation.approval_id = approval_id_value
              AND revocation.revoked_at <= NEW.reference_time
        ) THEN
            RAISE EXCEPTION 'revoked approval cannot satisfy evidence'
            USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER evidence_unrevoked_approval
AFTER INSERT ON core_evidence DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_unrevoked_manual_evidence();
CREATE CONSTRAINT TRIGGER mapping_unrevoked_approval
AFTER INSERT ON core_criterionevidence DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_unrevoked_manual_evidence();
"""
DROP_REVOCATION_SQL = """
DROP TRIGGER IF EXISTS mapping_unrevoked_approval ON core_criterionevidence;
DROP TRIGGER IF EXISTS evidence_unrevoked_approval ON core_evidence;
DROP FUNCTION IF EXISTS core_validate_unrevoked_manual_evidence();
DROP TRIGGER IF EXISTS policyoverriderevocation_immutable
ON core_policyoverriderevocation;
DROP TRIGGER IF EXISTS approvalrevocation_immutable
ON core_approvalrevocation;
ALTER TABLE core_policyoverriderevocation
DROP CONSTRAINT IF EXISTS policyoverriderevocation_override_tenant_fk;
ALTER TABLE core_approvalrevocation
DROP CONSTRAINT IF EXISTS approvalrevocation_approval_tenant_fk;
"""


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0008_deterministic_intent_policy_evidence"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="policyversion",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ApprovalRevocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("authority_path", models.CharField(max_length=1000)),
                ("reason", models.CharField(max_length=2000)),
                (
                    "revoked_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.approval"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="core_approval_revocation_org_id_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyOverrideRevocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("authority_path", models.CharField(max_length=1000)),
                ("reason", models.CharField(max_length=2000)),
                (
                    "revoked_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "policy_override",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.policyoverride"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="core_policy_override_revoke_org_id_unique",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=REVOCATION_SQL,
            reverse_sql=DROP_REVOCATION_SQL,
        ),
    ]
