# Generated by Django 5.2.5 on 2026-07-28 14:49

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONS = (
    ("core_pullrequest", "repository_id", "core_repository"),
    ("core_pullrequestrevision", "pull_request_id", "core_pullrequest"),
    ("core_pullrequestrevision", "diff_artifact_id", "core_immutableartifact"),
    ("core_diffchunk", "pull_request_revision_id", "core_pullrequestrevision"),
    ("core_assurancerun", "repository_id", "core_repository"),
    ("core_assurancerun", "pull_request_revision_id", "core_pullrequestrevision"),
    ("core_assurancerun", "work_item_revision_id", "core_workitemrevision"),
    ("core_assurancerun", "diff_artifact_id", "core_immutableartifact"),
    ("core_assurancerun", "context_packet_id", "core_contextpacketrecord"),
    ("core_assurancerun", "policy_evaluation_id", "core_policyevaluation"),
    ("core_assurancecheck", "assurance_run_id", "core_assurancerun"),
    ("core_evaluatortask", "assurance_run_id", "core_assurancerun"),
    ("core_evaluatortask", "repository_id", "core_repository"),
    ("core_evaluatortask", "request_artifact_id", "core_immutableartifact"),
    ("core_evaluatortask", "result_artifact_id", "core_immutableartifact"),
    ("core_evaluatorattempt", "evaluator_task_id", "core_evaluatortask"),
    ("core_finding", "pull_request_id", "core_pullrequest"),
    ("core_finding", "first_run_id", "core_assurancerun"),
    ("core_finding", "latest_run_id", "core_assurancerun"),
    ("core_findingdecision", "finding_id", "core_finding"),
    ("core_findingoccurrence", "finding_id", "core_finding"),
    ("core_findingoccurrence", "assurance_run_id", "core_assurancerun"),
    ("core_readinessdecision", "assurance_run_id", "core_assurancerun"),
    ("core_assurancereport", "assurance_run_id", "core_assurancerun"),
    ("core_assurancereport", "artifact_id", "core_immutableartifact"),
    ("core_assuranceknowledgeproposal", "assurance_run_id", "core_assurancerun"),
    (
        "core_assuranceknowledgeproposal",
        "knowledge_proposal_id",
        "core_knowledgeproposal",
    ),
)


def _tenant_constraint(table: str, column: str) -> str:
    return (f"{table.removeprefix('core_')}_{column.removesuffix('_id')}_tenant_fk")[:63]


SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} ADD CONSTRAINT {_tenant_constraint(table, column)} "
    f"FOREIGN KEY (organization_id, {column}) "
    f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    for table, column, target in SAME_TENANT_RELATIONS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {_tenant_constraint(table, column)};"
    for table, column, _target in reversed(SAME_TENANT_RELATIONS)
)

IMMUTABLE_TABLES = (
    "core_pullrequestrevision",
    "core_diffchunk",
    "core_assurancecheck",
    "core_evaluatorattempt",
    "core_findingdecision",
    "core_findingoccurrence",
    "core_readinessdecision",
    "core_assurancereport",
    "core_assuranceknowledgeproposal",
)
IMMUTABILITY_SQL = """
CREATE FUNCTION core_reject_assurance_immutable_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is immutable', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
""" + "\n".join(
    f"""
CREATE TRIGGER {table.removeprefix("core_")}_immutable
BEFORE UPDATE OR DELETE ON {table}
FOR EACH ROW EXECUTE FUNCTION core_reject_assurance_immutable_change();
"""
    for table in IMMUTABLE_TABLES
)
DROP_IMMUTABILITY_SQL = (
    "\n".join(
        f"DROP TRIGGER IF EXISTS {table.removeprefix('core_')}_immutable ON {table};"
        for table in reversed(IMMUTABLE_TABLES)
    )
    + "\nDROP FUNCTION IF EXISTS core_reject_assurance_immutable_change();"
)


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0010_criterion_evidence_semantic_eligibility"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="AssuranceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("NOT_AVAILABLE", "Not Available"),
                        ],
                        max_length=20,
                    ),
                ),
                ("blocking", models.BooleanField(default=True)),
                ("summary", models.CharField(max_length=2000)),
                ("evidence_ids", models.JSONField(default=list)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssuranceKnowledgeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("classification", models.CharField(max_length=20)),
                ("confidence", models.CharField(max_length=16)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssuranceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("markdown", models.TextField()),
                ("html", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("renderer_version", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiffChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("path", models.CharField(max_length=1000)),
                ("classification", models.CharField(max_length=40)),
                ("old_start", models.PositiveIntegerField()),
                ("old_count", models.PositiveIntegerField()),
                ("new_start", models.PositiveIntegerField()),
                ("new_count", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("char_count", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluatorAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                ("claimant", models.CharField(max_length=200)),
                ("event", models.CharField(max_length=24)),
                ("request_hash", models.CharField(max_length=64)),
                ("result_hash", models.CharField(blank=True, max_length=64)),
                ("usage", models.JSONField(default=dict)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluatorTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLAIMED", "Claimed"),
                            ("SUBMITTED", "Submitted"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("claimant", models.CharField(blank=True, max_length=200)),
                ("claim_token_hash", models.CharField(blank=True, max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("fingerprint", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DETERMINISTIC", "Deterministic"),
                            ("POLICY", "Policy"),
                            ("EVIDENCE", "Evidence"),
                            ("MODEL", "Model"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("BLOCKING", "Blocking"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("ADVISORY", "Advisory"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("PROVEN", "Proven"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("explanation", models.TextField()),
                ("path", models.CharField(blank=True, max_length=1000)),
                ("line", models.PositiveIntegerField(blank=True, null=True)),
                ("citations", models.JSONField(default=list)),
                ("evidence_ids", models.JSONField(default=list)),
                ("criterion_codes", models.JSONField(default=list)),
                ("uncertainty", models.CharField(max_length=2000)),
                ("suggested_resolution", models.CharField(max_length=2000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("DISMISSED", "Dismissed"),
                            ("RISK_ACCEPTED", "Risk Accepted"),
                            ("RESOLVED", "Resolved"),
                            ("OBSOLETE", "Obsolete"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_state", models.CharField(max_length=20)),
                ("to_state", models.CharField(max_length=20)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("authority_path", models.CharField(max_length=1000)),
                ("reason", models.CharField(max_length=2000)),
                (
                    "decided_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FindingOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("MERGED", "Merged"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("current_head_commit", models.CharField(max_length=40)),
                ("current_revision_number", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PullRequestRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("base_commit", models.CharField(max_length=40)),
                ("head_commit", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("target_branch", models.CharField(max_length=300)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("MERGED", "Merged"), ("CLOSED", "Closed")],
                        max_length=16,
                    ),
                ),
                ("diff_hash", models.CharField(max_length=64)),
                ("input_hash", models.CharField(max_length=64)),
                ("changed_paths", models.JSONField(default=list)),
                ("classification_summary", models.JSONField(default=dict)),
                ("limitations", models.JSONField(default=list)),
                ("ingested_by_type", models.CharField(max_length=20)),
                ("ingested_by_id", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadinessDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                ("reason_codes", models.JSONField(default=list)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "decided_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="assurancerun",
            name="core_assurance_one_head_summary",
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="context_packet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.contextpacketrecord",
            ),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="diff_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diff_assurance_runs",
                to="core.immutableartifact",
            ),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="evaluator_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="evidence_bundle_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="failure_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="input_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="limitations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="policy_bundle_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="policy_evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.policyevaluation",
            ),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="readiness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLOCKED", "BLOCKED"),
                    ("READY_WITH_WARNINGS", "READY_WITH_WARNINGS"),
                    ("READY_FOR_HUMAN_REVIEW", "READY_FOR_HUMAN_REVIEW"),
                    ("STALE", "STALE"),
                    ("FAILED", "FAILED"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assurance_runs",
                to="core.repository",
            ),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="requirements_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="trigger_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="work_item_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.workitemrevision",
            ),
        ),
        migrations.AlterField(
            model_name="assurancerun",
            name="context_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_assurance_runs",
                to="core.immutableartifact",
            ),
        ),
        migrations.AlterField(
            model_name="immutableartifact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CONTEXT_PACKET", "Context Packet"),
                    ("DIFF_ARTIFACT", "Diff Artifact"),
                    ("EVIDENCE_MANIFEST", "Evidence Manifest"),
                    ("EVALUATOR_REQUEST", "Evaluator Request"),
                    ("EVALUATOR_RESULT", "Evaluator Result"),
                    ("ASSURANCE_REPORT", "Assurance Report"),
                    ("RENDERED_EXTERNAL_CONTENT", "Rendered External Content"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="assurancecheck",
            name="assurance_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
            ),
        ),
        migrations.AddField(
            model_name="assurancecheck",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="assuranceknowledgeproposal",
            name="assurance_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
            ),
        ),
        migrations.AddField(
            model_name="assuranceknowledgeproposal",
            name="knowledge_proposal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeproposal"
            ),
        ),
        migrations.AddField(
            model_name="assuranceknowledgeproposal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="assurancereport",
            name="artifact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.immutableartifact"
            ),
        ),
        migrations.AddField(
            model_name="assurancereport",
            name="assurance_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
            ),
        ),
        migrations.AddField(
            model_name="assurancereport",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="diffchunk",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="evaluatorattempt",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="assurance_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
            ),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.repository"
            ),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="request_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluator_request_tasks",
                to="core.immutableartifact",
            ),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="result_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluator_result_tasks",
                to="core.immutableartifact",
            ),
        ),
        migrations.AddField(
            model_name="evaluatorattempt",
            name="evaluator_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.evaluatortask"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="first_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="first_findings",
                to="core.assurancerun",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="latest_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="latest_findings",
                to="core.assurancerun",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="findingdecision",
            name="finding",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.finding"),
        ),
        migrations.AddField(
            model_name="findingdecision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="findingoccurrence",
            name="assurance_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
            ),
        ),
        migrations.AddField(
            model_name="findingoccurrence",
            name="finding",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.finding"),
        ),
        migrations.AddField(
            model_name="findingoccurrence",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.repository"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="pull_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.pullrequest"
            ),
        ),
        migrations.AddField(
            model_name="pullrequestrevision",
            name="diff_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.immutableartifact"
            ),
        ),
        migrations.AddField(
            model_name="pullrequestrevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="pullrequestrevision",
            name="pull_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.pullrequest"
            ),
        ),
        migrations.AddField(
            model_name="diffchunk",
            name="pull_request_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.pullrequestrevision"
            ),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="pull_request_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.pullrequestrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "repository_external_id",
                    "pull_request_number",
                    "head_commit",
                    "input_hash",
                ),
                name="core_assurance_one_head_summary",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("input_hash", ""), ("input_hash__regex", "^[a-f0-9]{64}$"), _connector="OR"
                ),
                name="core_assurance_input_hash_sha",
            ),
        ),
        migrations.AddField(
            model_name="readinessdecision",
            name="assurance_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
            ),
        ),
        migrations.AddField(
            model_name="readinessdecision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancecheck",
            constraint=models.UniqueConstraint(
                fields=("organization", "assurance_run", "position"),
                name="core_assurance_check_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancecheck",
            constraint=models.UniqueConstraint(
                fields=("organization", "assurance_run", "code"),
                name="core_assurance_check_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancecheck",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_assurance_check_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancecheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_hash__regex", "^[a-f0-9]{64}$")),
                name="core_assurance_check_input_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="assuranceknowledgeproposal",
            constraint=models.UniqueConstraint(
                fields=("organization", "assurance_run", "input_hash"),
                name="core_assurance_proposal_input_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assuranceknowledgeproposal",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_assurance_proposal_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assuranceknowledgeproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_hash__regex", "^[a-f0-9]{64}$")),
                name="core_assurance_proposal_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancereport",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_assurance_report_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancereport",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_assurance_report_sha",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluatortask",
            index=models.Index(
                fields=["organization", "repository", "state", "created_at"],
                name="core_evaluator_task_claim_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_evaluatortask_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_evaluator_task_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="core_evaluator_attempt_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatorattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "evaluator_task", "attempt", "event"),
                name="core_evaluator_attempt_event_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatorattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_evaluator_attempt_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatorattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gte", 1)), name="core_evaluator_attempt_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatorattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[a-f0-9]{64}$")),
                name="core_evaluator_attempt_request_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="findingdecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_finding_decision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="findingoccurrence",
            constraint=models.UniqueConstraint(
                fields=("organization", "finding", "assurance_run"),
                name="core_finding_occurrence_run_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="findingoccurrence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_finding_occurrence_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="findingoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_hash__regex", "^[a-f0-9]{64}$")),
                name="core_finding_occurrence_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_pullrequest_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "number"),
                name="core_pull_request_repo_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_pull_request_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_head_commit__regex", "^[a-f0-9]{40}$")),
                name="core_pull_request_head_commit_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_revision_number__gte", 1), ("number__gte", 1)),
                name="core_pull_request_numbers_gte_1",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["organization", "pull_request", "state", "severity"],
                name="core_finding_pr_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_finding_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("organization", "pull_request", "fingerprint"),
                name="core_finding_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_finding_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(("fingerprint__regex", "^[a-f0-9]{64}$")),
                name="core_finding_fingerprint_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_pr_revision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "pull_request", "revision"),
                name="core_pr_revision_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "pull_request", "input_hash"),
                name="core_pr_revision_input_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_pr_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_commit__regex", "^[a-f0-9]{40}$")),
                name="core_pr_revision_base_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("head_commit__regex", "^[a-f0-9]{40}$")),
                name="core_pr_revision_head_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("diff_hash__regex", "^[a-f0-9]{64}$")),
                name="core_pr_revision_diff_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_hash__regex", "^[a-f0-9]{64}$")),
                name="core_pr_revision_input_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="diffchunk",
            constraint=models.UniqueConstraint(
                fields=("organization", "pull_request_revision", "position"),
                name="core_diff_chunk_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="diffchunk",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_diff_chunk_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="diffchunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="core_diff_chunk_position_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="diffchunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_diff_chunk_hash_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinessdecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_readiness_decision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="readinessdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_hash__regex", "^[a-f0-9]{64}$")),
                name="core_readiness_input_sha",
            ),
        ),
        migrations.AlterField(
            model_name="readinessdecision",
            name="status",
            field=models.CharField(
                choices=[
                    ("BLOCKED", "Blocked"),
                    ("READY_WITH_WARNINGS", "Ready With Warnings"),
                    ("READY_FOR_HUMAN_REVIEW", "Ready For Human Review"),
                    ("STALE", "Stale"),
                    ("FAILED", "Failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="readinessdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "BLOCKED",
                            "READY_WITH_WARNINGS",
                            "READY_FOR_HUMAN_REVIEW",
                            "STALE",
                            "FAILED",
                        ],
                    )
                ),
                name="core_readiness_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="core_assurance_run_org_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeproposal",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="core_knowledge_proposal_org_id_unique",
            ),
        ),
        migrations.RunSQL(
            sql=SAME_TENANT_SQL,
            reverse_sql=DROP_SAME_TENANT_SQL,
        ),
        migrations.RunSQL(
            sql=IMMUTABILITY_SQL,
            reverse_sql=DROP_IMMUTABILITY_SQL,
        ),
    ]
