# Generated by Django 5.2.5 on 2026-07-30 09:53

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONS = (
    ("core_githubinstallation", "service_identity_id", "core_serviceidentity"),
    ("core_githubrepositorybinding", "installation_id", "core_githubinstallation"),
    ("core_githubrepositorybinding", "repository_id", "core_repository"),
    ("core_githubrepositorybinding", "access_scope_id", "core_accessscope"),
    ("core_githubrepositorybinding", "work_item_revision_id", "core_workitemrevision"),
    ("core_githubwebhookdelivery", "installation_id", "core_githubinstallation"),
    ("core_githubwebhookdelivery", "repository_binding_id", "core_githubrepositorybinding"),
    ("core_githubeventprocessing", "delivery_id", "core_githubwebhookdelivery"),
    ("core_githubcheckobservation", "repository_binding_id", "core_githubrepositorybinding"),
    ("core_githubcheckobservation", "delivery_id", "core_githubwebhookdelivery"),
    (
        "core_githubpullrequestobservation",
        "repository_binding_id",
        "core_githubrepositorybinding",
    ),
    ("core_githubpullrequestobservation", "delivery_id", "core_githubwebhookdelivery"),
    (
        "core_githubpullrequestobservation",
        "pull_request_revision_id",
        "core_pullrequestrevision",
    ),
    ("core_githubpublication", "repository_binding_id", "core_githubrepositorybinding"),
    ("core_githubpublication", "pull_request_id", "core_pullrequest"),
    ("core_githubpublication", "assurance_run_id", "core_assurancerun"),
    ("core_githubwriteintent", "publication_id", "core_githubpublication"),
    ("core_githubwriteintent", "assurance_run_id", "core_assurancerun"),
    ("core_githubwriteattempt", "write_intent_id", "core_githubwriteintent"),
)


def _tenant_constraint(table: str, column: str) -> str:
    return (f"{table.removeprefix('core_')}_{column.removesuffix('_id')}_tenant_fk")[:63]


SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} ADD CONSTRAINT {_tenant_constraint(table, column)} "
    f"FOREIGN KEY (organization_id, {column}) "
    f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    for table, column, target in SAME_TENANT_RELATIONS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {_tenant_constraint(table, column)};"
    for table, column, _target in reversed(SAME_TENANT_RELATIONS)
)

IMMUTABLE_TABLES = (
    "core_githubwebhookdelivery",
    "core_githubcheckobservation",
    "core_githubpullrequestobservation",
    "core_githubwriteattempt",
)
IMMUTABILITY_SQL = """
CREATE FUNCTION core_reject_github_immutable_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is immutable', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
""" + "\n".join(
    f"""
CREATE TRIGGER {table.removeprefix("core_")}_immutable
BEFORE UPDATE OR DELETE ON {table}
FOR EACH ROW EXECUTE FUNCTION core_reject_github_immutable_change();
"""
    for table in IMMUTABLE_TABLES
)
DROP_IMMUTABILITY_SQL = (
    "\n".join(
        f"DROP TRIGGER IF EXISTS {table.removeprefix('core_')}_immutable ON {table};"
        for table in reversed(IMMUTABLE_TABLES)
    )
    + "\nDROP FUNCTION IF EXISTS core_reject_github_immutable_change();"
)

WRITE_INTENT_IMMUTABILITY_SQL = """
CREATE FUNCTION core_guard_github_write_intent_content() RETURNS trigger AS $$
BEGIN
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.publication_id IS DISTINCT FROM OLD.publication_id
       OR NEW.assurance_run_id IS DISTINCT FROM OLD.assurance_run_id
       OR NEW.head_commit IS DISTINCT FROM OLD.head_commit
       OR NEW.rendered_payload IS DISTINCT FROM OLD.rendered_payload
       OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'GitHub write intent content is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER githubwriteintent_content_immutable
BEFORE UPDATE ON core_githubwriteintent
FOR EACH ROW EXECUTE FUNCTION core_guard_github_write_intent_content();
"""
DROP_WRITE_INTENT_IMMUTABILITY_SQL = """
DROP TRIGGER IF EXISTS githubwriteintent_content_immutable ON core_githubwriteintent;
DROP FUNCTION IF EXISTS core_guard_github_write_intent_content();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0011_manual_diff_assurance"),
    ]

    operations: ClassVar = [
        migrations.RemoveConstraint(
            model_name="accessgrant",
            name="core_access_grant_membership_unique",
        ),
        migrations.RemoveConstraint(
            model_name="accessgrant",
            name="core_access_grant_service_unique",
        ),
        migrations.AddConstraint(
            model_name="accessgrant",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "membership",
                    "service_identity",
                    "repository",
                    "source_connection",
                    "action",
                ),
                name="core_access_grant_principal_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("external_id", models.PositiveBigIntegerField()),
                ("account_id", models.PositiveBigIntegerField()),
                ("account_login", models.CharField(max_length=300)),
                ("account_type", models.CharField(max_length=32)),
                ("repository_selection", models.CharField(max_length=16)),
                ("permissions", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "service_identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_installation",
                        to="core.serviceidentity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GitHubRepositoryBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("external_repository_id", models.PositiveBigIntegerField()),
                ("full_name", models.CharField(max_length=600)),
                ("default_branch", models.CharField(max_length=300)),
                ("is_private", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_assurance", models.BooleanField(default=True)),
                ("policy_version_ids", models.JSONField(default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubinstallation"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_binding",
                        to="core.repository",
                    ),
                ),
                (
                    "work_item_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.workitemrevision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GitHubPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[("CHECK", "Check"), ("COMMENT", "Comment")], max_length=16
                    ),
                ),
                ("head_commit", models.CharField(max_length=40)),
                ("is_current", models.BooleanField(default=True)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("external_url", models.URLField(blank=True, max_length=2000)),
                ("last_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "assurance_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pullrequest"
                    ),
                ),
                (
                    "repository_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.githubrepositorybinding",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GitHubWebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("delivery_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("payload_checksum", models.CharField(max_length=64)),
                ("normalized_payload", models.JSONField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubinstallation"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.githubrepositorybinding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubPullRequestObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_pull_request_id", models.PositiveBigIntegerField()),
                ("head_repository_id", models.PositiveBigIntegerField()),
                ("head_ref", models.CharField(max_length=300)),
                ("is_fork", models.BooleanField(default=False)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "pull_request_revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pullrequestrevision"
                    ),
                ),
                (
                    "repository_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.githubrepositorybinding",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubwebhookdelivery"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubEventProcessing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("result_identifiers", models.JSONField(default=dict)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubwebhookdelivery"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GitHubCheckObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CHECK_RUN", "Check Run"),
                            ("CHECK_SUITE", "Check Suite"),
                            ("WORKFLOW_RUN", "Workflow Run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=300)),
                ("head_commit", models.CharField(max_length=40)),
                ("status", models.CharField(max_length=32)),
                ("conclusion", models.CharField(blank=True, max_length=32)),
                ("details_url", models.URLField(blank=True, max_length=2000)),
                ("pull_request_numbers", models.JSONField(default=list)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.githubrepositorybinding",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubwebhookdelivery"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubWriteIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("head_commit", models.CharField(max_length=40)),
                ("rendered_payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("RETRY", "Retry"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_owner", models.CharField(blank=True, max_length=200)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("external_url", models.URLField(blank=True, max_length=2000)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "assurance_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.assurancerun"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubpublication"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubWriteAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                ("outcome", models.CharField(max_length=24)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("response_metadata", models.JSONField(default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "write_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.githubwriteintent"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="githubinstallation",
            index=models.Index(
                fields=["external_id", "state"], name="core_gh_install_ext_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="core_githubinstallation_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.UniqueConstraint(
                fields=("external_id",), name="core_gh_install_external_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_install_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", False), ("state", "REVOKED")),
                    models.Q(("revoked_at__isnull", True), ("state__in", ["ACTIVE", "SUSPENDED"])),
                    _connector="OR",
                ),
                name="core_gh_install_revoked_time",
            ),
        ),
        migrations.AddIndex(
            model_name="githubrepositorybinding",
            index=models.Index(
                fields=["installation", "external_repository_id", "is_active"],
                name="core_gh_repo_install_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubrepositorybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="core_githubrepositorybinding_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubrepositorybinding",
            constraint=models.UniqueConstraint(
                fields=("installation", "external_repository_id"),
                name="core_gh_repo_install_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubrepositorybinding",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_repo_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubrepositorybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_active", True), ("revoked_at__isnull", True)),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="core_gh_repo_active_not_revoked",
            ),
        ),
        migrations.AddIndex(
            model_name="githubpublication",
            index=models.Index(
                fields=["repository_binding", "pull_request", "kind", "head_commit"],
                name="core_gh_publication_head_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="core_githubpublication_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpublication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("organization", "repository_binding", "pull_request", "kind"),
                name="core_gh_publication_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpublication",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "repository_binding",
                    "pull_request",
                    "kind",
                    "head_commit",
                ),
                name="core_gh_publication_head_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpublication",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_publication_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("head_commit__regex", "^[a-f0-9]{40}$")),
                name="core_gh_publication_head_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_payload_hash", ""),
                    ("last_payload_hash__regex", "^[a-f0-9]{64}$"),
                    _connector="OR",
                ),
                name="core_gh_publication_payload_sha",
            ),
        ),
        migrations.AddIndex(
            model_name="githubwebhookdelivery",
            index=models.Index(
                fields=["organization", "installation", "received_at"],
                name="core_gh_delivery_install_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwebhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("delivery_id",), name="core_gh_delivery_external_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwebhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_delivery_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwebhookdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_checksum__regex", "^[a-f0-9]{64}$")),
                name="core_gh_delivery_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpullrequestobservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_pr_observation_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpullrequestobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_hash__regex", "^[a-f0-9]{64}$")),
                name="core_gh_pr_observation_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubeventprocessing",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="core_githubeventprocessing_revision_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubeventprocessing",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_processing_org_id_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="githubcheckobservation",
            index=models.Index(
                fields=["repository_binding", "head_commit", "observed_at"],
                name="core_gh_check_head_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubcheckobservation",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "repository_binding",
                    "kind",
                    "external_id",
                    "payload_hash",
                ),
                name="core_gh_check_observation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubcheckobservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_check_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubcheckobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("head_commit__regex", "^[a-f0-9]{40}$")),
                name="core_gh_check_head_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubcheckobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_hash__regex", "^[a-f0-9]{64}$")),
                name="core_gh_check_payload_sha",
            ),
        ),
        migrations.AddIndex(
            model_name="githubwriteintent",
            index=models.Index(
                fields=["state", "available_at", "created_at"], name="core_gh_write_dispatch_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteintent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_write_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteintent",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="core_gh_write_idempotency_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("head_commit__regex", "^[a-f0-9]{40}$")),
                name="core_gh_write_head_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_hash__regex", "^[a-f0-9]{64}$")),
                name="core_gh_write_payload_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="core_gh_write_attempt_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "write_intent", "attempt"),
                name="core_gh_write_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubwriteattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_gh_write_attempt_org_id_unique"
            ),
        ),
        migrations.RunSQL(
            sql=SAME_TENANT_SQL,
            reverse_sql=DROP_SAME_TENANT_SQL,
        ),
        migrations.RunSQL(
            sql=IMMUTABILITY_SQL,
            reverse_sql=DROP_IMMUTABILITY_SQL,
        ),
        migrations.RunSQL(
            sql=WRITE_INTENT_IMMUTABILITY_SQL,
            reverse_sql=DROP_WRITE_INTENT_IMMUTABILITY_SQL,
        ),
    ]
