# Generated by Django 5.2.5 on 2026-07-31 00:38

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONS = (
    ("core_knowledgeproposalscope", "knowledge_proposal_id", "core_knowledgeproposal"),
    ("core_knowledgeproposalscope", "repository_id", "core_repository"),
    ("core_knowledgeproposalscope", "access_scope_id", "core_accessscope"),
    ("core_knowledgeproposalscope", "assertion_id", "core_knowledgeassertion"),
    ("core_repositoryprofile", "repository_id", "core_repository"),
)


def _tenant_constraint(table: str, column: str) -> str:
    return (f"{table.removeprefix('core_')}_{column.removesuffix('_id')}_tenant_fk")[:63]


SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} ADD CONSTRAINT {_tenant_constraint(table, column)} "
    f"FOREIGN KEY (organization_id, {column}) "
    f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    for table, column, target in SAME_TENANT_RELATIONS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {_tenant_constraint(table, column)};"
    for table, column, _target in reversed(SAME_TENANT_RELATIONS)
)


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0014_knowledge_proposal_immutability"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.CreateModel(
            name="KnowledgeProposalScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.accessscope"
                    ),
                ),
                (
                    "assertion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.knowledgeassertion",
                    ),
                ),
                (
                    "knowledge_proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeproposal"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="core_proposal_scope_org_id_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationProductSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("retention_days", models.PositiveIntegerField(default=365)),
                (
                    "model_processing",
                    models.CharField(
                        choices=[
                            ("DISABLED", "Disabled"),
                            ("REDACTED_ONLY", "Redacted Only"),
                            ("ALLOWED", "Allowed"),
                        ],
                        default="REDACTED_ONLY",
                        max_length=24,
                    ),
                ),
                (
                    "skill_distribution",
                    models.CharField(
                        choices=[("SELF_SERVICE", "Self Service"), ("MANAGED", "Managed")],
                        default="SELF_SERVICE",
                        max_length=24,
                    ),
                ),
                (
                    "assurance_mode",
                    models.CharField(
                        choices=[("OBSERVE", "Observe"), ("EVIDENCE", "Evidence")],
                        default="OBSERVE",
                        max_length=24,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("retention_days__gte", 1), ("retention_days__lte", 3650)
                        ),
                        name="core_product_settings_retention_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RepositoryProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("purpose", models.TextField(blank=True)),
                ("owning_team", models.CharField(blank=True, max_length=300)),
                ("products", models.JSONField(default=list)),
                ("systems", models.JSONField(default=list)),
                ("runtime", models.JSONField(default=list)),
                ("setup_commands", models.JSONField(default=list)),
                ("required_checks", models.JSONField(default=list)),
                ("sensitive_paths", models.JSONField(default=list)),
                ("unsupported_or_ambiguous", models.JSONField(default=list)),
                ("source_references", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROPOSED", "Proposed"),
                            ("CONFIRMED", "Confirmed"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("confirmed_by_type", models.CharField(blank=True, max_length=20)),
                ("confirmed_by_id", models.CharField(blank=True, max_length=200)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.repository"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="core_repositoryprofile_revision_gte_1",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="core_repository_profile_org_id_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("confirmed_at__isnull", False),
                                ("confirmed_by_id__gt", ""),
                                ("confirmed_by_type__gt", ""),
                                ("status", "CONFIRMED"),
                            ),
                            models.Q(
                                models.Q(("status", "CONFIRMED"), _negated=True),
                                ("confirmed_at__isnull", True),
                                ("confirmed_by_id", ""),
                                ("confirmed_by_type", ""),
                            ),
                            _connector="OR",
                        ),
                        name="core_repository_profile_confirmation_coherent",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=SAME_TENANT_SQL,
            reverse_sql=DROP_SAME_TENANT_SQL,
        ),
    ]
