# Generated by Django 5.2.5 on 2026-07-31 15:21

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SAME_TENANT_RELATIONS = (
    ("core_canvasview", "repository_id", "core_repository"),
    ("core_canvasview", "access_scope_id", "core_accessscope"),
    ("core_canvasview", "owner_membership_id", "core_membership"),
    ("core_canvasviewrevision", "canvas_view_id", "core_canvasview"),
    ("core_canvasshare", "canvas_view_id", "core_canvasview"),
    ("core_canvasshare", "view_revision_id", "core_canvasviewrevision"),
    ("core_canvasshare", "recipient_membership_id", "core_membership"),
    ("core_canvasnodeplacement", "view_revision_id", "core_canvasviewrevision"),
    ("core_canvasnodeplacement", "entity_id", "core_knowledgeentity"),
    ("core_canvasnodeplacement", "group_id", "core_canvasgroup"),
    ("core_canvasgroup", "view_revision_id", "core_canvasviewrevision"),
    ("core_canvasfilter", "view_revision_id", "core_canvasviewrevision"),
    ("core_canvaslayer", "view_revision_id", "core_canvasviewrevision"),
    ("core_canvasannotation", "view_revision_id", "core_canvasviewrevision"),
    ("core_canvasannotation", "entity_id", "core_knowledgeentity"),
)


def _tenant_constraint(table: str, column: str) -> str:
    return (f"{table.removeprefix('core_')}_{column.removesuffix('_id')}_tenant_fk")[:63]


SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} ADD CONSTRAINT {_tenant_constraint(table, column)} "
    f"FOREIGN KEY (organization_id, {column}) "
    f"REFERENCES {target} (organization_id, id) DEFERRABLE INITIALLY DEFERRED;"
    for table, column, target in SAME_TENANT_RELATIONS
)
DROP_SAME_TENANT_SQL = "\n".join(
    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {_tenant_constraint(table, column)};"
    for table, column, _target in reversed(SAME_TENANT_RELATIONS)
)

IMMUTABLE_TABLES = (
    "core_canvasviewrevision",
    "core_canvasnodeplacement",
    "core_canvasgroup",
    "core_canvasfilter",
    "core_canvaslayer",
    "core_canvasannotation",
)
IMMUTABILITY_SQL = """
CREATE FUNCTION core_reject_canvas_revision_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Canvas revisions and children are append-only' USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql;
""" + "\n".join(
    f"CREATE TRIGGER {table.removeprefix('core_')}_immutable "
    f"BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW "
    "EXECUTE FUNCTION core_reject_canvas_revision_mutation();"
    for table in IMMUTABLE_TABLES
)
DROP_IMMUTABILITY_SQL = (
    "\n".join(
        f"DROP TRIGGER IF EXISTS {table.removeprefix('core_')}_immutable ON {table};"
        for table in reversed(IMMUTABLE_TABLES)
    )
    + "\nDROP FUNCTION IF EXISTS core_reject_canvas_revision_mutation();"
)

LINK_GUARD_SQL = """
CREATE FUNCTION core_guard_canvas_share_link() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM core_canvasviewrevision revision
        WHERE revision.id = NEW.view_revision_id
          AND revision.canvas_view_id = NEW.canvas_view_id
          AND revision.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'Canvas share revision does not belong to its view'
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION core_guard_canvas_placement_link() RETURNS trigger AS $$
BEGIN
    IF NEW.group_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM core_canvasgroup canvas_group
        WHERE canvas_group.id = NEW.group_id
          AND canvas_group.view_revision_id = NEW.view_revision_id
          AND canvas_group.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'Canvas placement group does not belong to its revision'
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER canvasshare_link_guard BEFORE INSERT OR UPDATE ON core_canvasshare
FOR EACH ROW EXECUTE FUNCTION core_guard_canvas_share_link();
CREATE TRIGGER canvasplacement_link_guard BEFORE INSERT OR UPDATE ON core_canvasnodeplacement
FOR EACH ROW EXECUTE FUNCTION core_guard_canvas_placement_link();
"""
DROP_LINK_GUARD_SQL = """
DROP TRIGGER IF EXISTS canvasplacement_link_guard ON core_canvasnodeplacement;
DROP TRIGGER IF EXISTS canvasshare_link_guard ON core_canvasshare;
DROP FUNCTION IF EXISTS core_guard_canvas_placement_link();
DROP FUNCTION IF EXISTS core_guard_canvas_share_link();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0015_knowledgeproposalscope_organizationproductsettings_and_more"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.AlterField(
            model_name="knowledgeentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("GOAL", "Goal"),
                    ("METRIC", "Metric"),
                    ("INITIATIVE", "Initiative"),
                    ("PRODUCT", "Product"),
                    ("OWNER", "Owner"),
                    ("ENVIRONMENT", "Environment"),
                    ("CUSTOMER_COMMITMENT", "Customer Commitment"),
                    ("ARCHITECTURAL_DECISION", "Architectural Decision"),
                    ("ACCEPTANCE_CRITERION", "Acceptance Criterion"),
                    ("RELEASE", "Release"),
                    ("TEAM", "Team"),
                    ("REPOSITORY", "Repository"),
                    ("SERVICE", "Service"),
                    ("COMPONENT", "Component"),
                    ("API", "Api"),
                    ("DATA_ASSET", "Data Asset"),
                    ("WORK_ITEM", "Work Item"),
                    ("TASK", "Task"),
                    ("PULL_REQUEST", "Pull Request"),
                    ("EVIDENCE", "Evidence"),
                    ("RISK", "Risk"),
                    ("INCIDENT", "Incident"),
                    ("CONTROL", "Control"),
                    ("DECISION", "Decision"),
                    ("POLICY", "Policy"),
                    ("REQUIREMENT", "Requirement"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgerelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("GOAL_MEASURED_BY_METRIC", "Goal Measured By Metric"),
                    ("INITIATIVE_SUPPORTS_GOAL", "Initiative Supports Goal"),
                    ("INITIATIVE_OWNED_BY_TEAM", "Initiative Owned By Team"),
                    ("INITIATIVE_AFFECTS_PRODUCT", "Initiative Affects Product"),
                    ("PRODUCT_IMPLEMENTED_BY_REPOSITORY", "Product Implemented By Repository"),
                    ("COMPONENT_BELONGS_TO_PRODUCT", "Component Belongs To Product"),
                    ("REPOSITORY_OWNED_BY_TEAM", "Repository Owned By Team"),
                    ("REPOSITORY_CONTAINS_COMPONENT", "Repository Contains Component"),
                    ("SERVICE_IMPLEMENTED_BY_REPOSITORY", "Service Implemented By Repository"),
                    ("SERVICE_DEPENDS_ON_SERVICE", "Service Depends On Service"),
                    ("API_PROVIDED_BY_SERVICE", "Api Provided By Service"),
                    ("API_CONSUMED_BY_COMPONENT", "Api Consumed By Component"),
                    ("DATA_ASSET_USED_BY_SERVICE", "Data Asset Used By Service"),
                    ("DECISION_APPLIES_TO_ENTITY", "Decision Applies To Entity"),
                    ("POLICY_APPLIES_TO_ENTITY", "Policy Applies To Entity"),
                    ("RISK_AFFECTS_ENTITY", "Risk Affects Entity"),
                    ("INCIDENT_AFFECTED_ENTITY", "Incident Affected Entity"),
                    ("REQUIREMENT_SUPPORTS_INITIATIVE", "Requirement Supports Initiative"),
                    (
                        "REQUIREMENT_IMPLEMENTED_BY_PULL_REQUEST",
                        "Requirement Implemented By Pull Request",
                    ),
                    (
                        "ACCEPTANCE_CRITERION_VERIFIED_BY_EVIDENCE",
                        "Acceptance Criterion Verified By Evidence",
                    ),
                    ("TASK_CHANGES_ENTITY", "Task Changes Entity"),
                    ("PULL_REQUEST_CHANGES_ENTITY", "Pull Request Changes Entity"),
                    ("ENTITY_OWNED_BY_OWNER", "Entity Owned By Owner"),
                    ("ENTITY_REVIEWED_BY_TEAM", "Entity Reviewed By Team"),
                    ("OWNED_BY", "Owned By"),
                    ("MAINTAINED_BY", "Maintained By"),
                    ("DEPENDS_ON", "Depends On"),
                    ("MEASURED_BY", "Measured By"),
                    ("ADVANCES", "Advances"),
                    ("IMPLEMENTS", "Implements"),
                    ("PART_OF", "Part Of"),
                    ("AFFECTS", "Affects"),
                    ("GOVERNED_BY", "Governed By"),
                    ("EVIDENCED_BY", "Evidenced By"),
                    ("BLOCKED_BY", "Blocked By"),
                    ("CHANGES", "Changes"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgerelationship",
            name="source_entity_type",
            field=models.CharField(
                choices=[
                    ("GOAL", "Goal"),
                    ("METRIC", "Metric"),
                    ("INITIATIVE", "Initiative"),
                    ("PRODUCT", "Product"),
                    ("OWNER", "Owner"),
                    ("ENVIRONMENT", "Environment"),
                    ("CUSTOMER_COMMITMENT", "Customer Commitment"),
                    ("ARCHITECTURAL_DECISION", "Architectural Decision"),
                    ("ACCEPTANCE_CRITERION", "Acceptance Criterion"),
                    ("RELEASE", "Release"),
                    ("TEAM", "Team"),
                    ("REPOSITORY", "Repository"),
                    ("SERVICE", "Service"),
                    ("COMPONENT", "Component"),
                    ("API", "Api"),
                    ("DATA_ASSET", "Data Asset"),
                    ("WORK_ITEM", "Work Item"),
                    ("TASK", "Task"),
                    ("PULL_REQUEST", "Pull Request"),
                    ("EVIDENCE", "Evidence"),
                    ("RISK", "Risk"),
                    ("INCIDENT", "Incident"),
                    ("CONTROL", "Control"),
                    ("DECISION", "Decision"),
                    ("POLICY", "Policy"),
                    ("REQUIREMENT", "Requirement"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgerelationship",
            name="target_entity_type",
            field=models.CharField(
                choices=[
                    ("GOAL", "Goal"),
                    ("METRIC", "Metric"),
                    ("INITIATIVE", "Initiative"),
                    ("PRODUCT", "Product"),
                    ("OWNER", "Owner"),
                    ("ENVIRONMENT", "Environment"),
                    ("CUSTOMER_COMMITMENT", "Customer Commitment"),
                    ("ARCHITECTURAL_DECISION", "Architectural Decision"),
                    ("ACCEPTANCE_CRITERION", "Acceptance Criterion"),
                    ("RELEASE", "Release"),
                    ("TEAM", "Team"),
                    ("REPOSITORY", "Repository"),
                    ("SERVICE", "Service"),
                    ("COMPONENT", "Component"),
                    ("API", "Api"),
                    ("DATA_ASSET", "Data Asset"),
                    ("WORK_ITEM", "Work Item"),
                    ("TASK", "Task"),
                    ("PULL_REQUEST", "Pull Request"),
                    ("EVIDENCE", "Evidence"),
                    ("RISK", "Risk"),
                    ("INCIDENT", "Incident"),
                    ("CONTROL", "Control"),
                    ("DECISION", "Decision"),
                    ("POLICY", "Policy"),
                    ("REQUIREMENT", "Requirement"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CanvasGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="CanvasView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=1000)),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("STRATEGY", "Strategy"),
                            ("PRODUCT_SYSTEM", "Product System"),
                            ("INITIATIVE", "Initiative"),
                            ("RISK_POLICY", "Risk Policy"),
                            ("CHANGE_HISTORY", "Change History"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_by_type", models.CharField(max_length=20)),
                ("created_by_id", models.CharField(max_length=200)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "access_scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.accessscope",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "owner_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.membership"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CanvasViewRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("schema_version", models.CharField(default="1", max_length=16)),
                ("semantic_query", models.JSONField(default=dict)),
                ("presentation", models.JSONField(default=dict)),
                ("layout_algorithm", models.CharField(max_length=50)),
                ("layout_version", models.CharField(max_length=50)),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("created_by_type", models.CharField(max_length=20)),
                ("created_by_id", models.CharField(max_length=200)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "canvas_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasview"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CanvasShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_by_type", models.CharField(max_length=20)),
                ("created_by_id", models.CharField(max_length=200)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "recipient_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.membership",
                    ),
                ),
                (
                    "canvas_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasview"
                    ),
                ),
                (
                    "view_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasviewrevision"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CanvasNodePlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.knowledgeentity"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.canvasgroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "view_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasviewrevision"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="CanvasLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("key", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "view_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasviewrevision"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="canvasgroup",
            name="view_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.canvasviewrevision"
            ),
        ),
        migrations.CreateModel(
            name="CanvasFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("field", models.CharField(max_length=32)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Equals"),
                            ("CONTAINS", "Contains"),
                            ("IN", "In"),
                            ("SINCE", "Since"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "view_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasviewrevision"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="CanvasAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.CharField(max_length=2000)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.knowledgeentity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "view_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.canvasviewrevision"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.AddIndex(
            model_name="canvasview",
            index=models.Index(
                fields=["organization", "repository", "is_archived", "name"],
                name="core_canvas_view_repo_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasview",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_canvasview_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasview",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_view_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("organization", "created_by_type", "created_by_id", "name"),
                name="core_canvas_view_active_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasview",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="core_canvas_view_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasview",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_view_idem_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasview",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_view_request_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_revision_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "canvas_view", "revision"),
                name="core_canvas_revision_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "canvas_view", "idempotency_key"),
                name="core_canvas_revision_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="core_canvas_revision_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_revision_hash_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "1")), name="core_canvas_revision_schema_v1"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_revision_idem_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_revision_request_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_share_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="core_canvas_share_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_share_idem_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[a-f0-9]{64}$")),
                name="core_canvas_share_request_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasnodeplacement",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_place_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasnodeplacement",
            constraint=models.UniqueConstraint(
                fields=("organization", "view_revision", "entity"),
                name="core_canvas_place_entity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasnodeplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("x__gte", -1000000), ("x__lte", 1000000)),
                name="core_canvas_place_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasnodeplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("y__gte", -1000000), ("y__lte", 1000000)),
                name="core_canvas_place_y_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvaslayer",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_layer_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvaslayer",
            constraint=models.UniqueConstraint(
                fields=("organization", "view_revision", "key"), name="core_canvas_layer_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvaslayer",
            constraint=models.UniqueConstraint(
                fields=("organization", "view_revision", "position"),
                name="core_canvas_layer_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvaslayer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "key__in",
                        ["execution", "ownership", "dependencies", "governance", "provenance"],
                    )
                ),
                name="core_canvas_layer_key_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasgroup",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_group_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("width__gt", 0), ("width__lte", 1000000)),
                name="core_canvas_group_width_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("height__gt", 0), ("height__lte", 1000000)),
                name="core_canvas_group_height_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("x__gte", -1000000), ("x__lte", 1000000)),
                name="core_canvas_group_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("y__gte", -1000000), ("y__lte", 1000000)),
                name="core_canvas_group_y_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasfilter",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_filter_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasfilter",
            constraint=models.UniqueConstraint(
                fields=("organization", "view_revision", "position"),
                name="core_canvas_filter_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasfilter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("field__in", ["entity_type", "owner", "status", "time", "risk", "freshness"])
                ),
                name="core_canvas_filter_field_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasannotation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="core_canvas_note_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasannotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("x__gte", -1000000), ("x__lte", 1000000)),
                name="core_canvas_note_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasannotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("y__gte", -1000000), ("y__lte", 1000000)),
                name="core_canvas_note_y_range",
            ),
        ),
        migrations.RunSQL(SAME_TENANT_SQL, reverse_sql=DROP_SAME_TENANT_SQL),
        migrations.RunSQL(LINK_GUARD_SQL, reverse_sql=DROP_LINK_GUARD_SQL),
        migrations.RunSQL(IMMUTABILITY_SQL, reverse_sql=DROP_IMMUTABILITY_SQL),
    ]
