# Generated by Django 5.2.5 on 2026-07-31 18:01

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0016_organizational_canvas"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.AddField(
            model_name="canvasshare",
            name="revocation_idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="canvasshare",
            name="revocation_request_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="canvasshare",
            name="revoked_by_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="canvasshare",
            name="revoked_by_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("revocation_idempotency_key__isnull", True),
                        ("revocation_request_hash__isnull", True),
                        ("revoked_at__isnull", True),
                        ("revoked_by_id__isnull", True),
                        ("revoked_by_type__isnull", True),
                    ),
                    models.Q(
                        ("revocation_idempotency_key__isnull", False),
                        ("revocation_request_hash__isnull", False),
                        ("revoked_at__isnull", False),
                        ("revoked_by_id__isnull", False),
                        ("revoked_by_type__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="core_canvas_share_revoke_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revocation_idempotency_key__isnull", True),
                    ("revocation_idempotency_key__regex", "^[a-f0-9]{64}$"),
                    _connector="OR",
                ),
                name="core_canvas_share_revoke_idem_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="canvasshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revocation_request_hash__isnull", True),
                    ("revocation_request_hash__regex", "^[a-f0-9]{64}$"),
                    _connector="OR",
                ),
                name="core_canvas_share_revoke_request_sha256",
            ),
        ),
    ]
