# Generated by Django 5.2.5 on 2026-08-03 18:36

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0017_canvas_share_revocation"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.AddIndex(
            model_name="assertionprovenance",
            index=models.Index(
                fields=["organization", "assertion", "observed_at", "id"],
                name="core_assertprov_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeassertion",
            index=models.Index(
                condition=models.Q(("valid_until__isnull", True)),
                fields=["organization", "subject_key", "-observed_at", "-id"],
                name="core_assert_current_subj_idx",
            ),
        ),
    ]
