# Generated by Django 5.2.5 on 2026-08-04 15:06

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0019_canvas_view_bounded_list_index"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_hash", models.CharField(max_length=64)),
                ("channel", models.CharField(max_length=32)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("denied_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="RetentionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SCHEDULED_RETENTION", "Scheduled Retention"),
                            ("ORGANIZATION_DECOMMISSION", "Organization Decommission"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("cutoff_at", models.DateTimeField()),
                ("dry_run", models.BooleanField(default=False)),
                ("request_hash", models.CharField(max_length=64)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("summary", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="decommissioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DELETION_REQUESTED", "Deletion Requested"),
                    ("DECOMMISSIONED", "Decommissioned"),
                ],
                default="ACTIVE",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decommissioned_at__isnull", True),
                        ("deletion_requested_at__isnull", True),
                        ("lifecycle_state", "ACTIVE"),
                    ),
                    models.Q(
                        ("decommissioned_at__isnull", True),
                        ("deletion_requested_at__isnull", False),
                        ("lifecycle_state", "DELETION_REQUESTED"),
                    ),
                    models.Q(
                        ("decommissioned_at__isnull", False),
                        ("deletion_requested_at__isnull", False),
                        ("lifecycle_state", "DECOMMISSIONED"),
                    ),
                    _connector="OR",
                ),
                name="core_organization_lifecycle_coherent",
            ),
        ),
        migrations.AddField(
            model_name="ratelimitbucket",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="retentionrun",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.organization"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitbucket",
            index=models.Index(fields=["expires_at"], name="core_rate_bucket_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="ratelimitbucket",
            index=models.Index(
                condition=models.Q(("organization__isnull", True)),
                fields=["expires_at", "id"],
                name="core_rate_preauth_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ratelimitbucket",
            constraint=models.UniqueConstraint(
                fields=("organization", "identity_hash", "channel", "window_started_at"),
                name="core_rate_bucket_window_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="ratelimitbucket",
            constraint=models.CheckConstraint(
                condition=models.Q(("identity_hash__regex", "^[a-f0-9]{64}$")),
                name="core_rate_bucket_identity_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="ratelimitbucket",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("window_started_at"))),
                name="core_rate_bucket_expiry_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="ratelimitbucket",
            constraint=models.CheckConstraint(
                condition=models.Q(("denied_count__lte", models.F("request_count"))),
                name="core_rate_bucket_denied_lte_requests",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind", "request_hash"),
                name="core_retention_run_request_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[a-f0-9]{64}$")),
                name="core_retention_run_request_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True), ("error_code", ""), ("state", "RUNNING")
                    ),
                    models.Q(
                        ("completed_at__isnull", False), ("error_code", ""), ("state", "COMPLETED")
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("state", "FAILED"),
                        models.Q(("error_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="core_retention_run_state_coherent",
            ),
        ),
    ]
