# Generated by Django 5.2.13 on 2026-08-07

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import F, Q

SAME_TENANT_SQL = """
ALTER TABLE core_evidenceuploadauthorization
ADD CONSTRAINT evidence_upload_repository_tenant_fk
FOREIGN KEY (organization_id, repository_id)
REFERENCES core_repository (organization_id, id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE core_evidenceuploadauthorization
ADD CONSTRAINT evidence_upload_scope_tenant_fk
FOREIGN KEY (organization_id, access_scope_id)
REFERENCES core_accessscope (organization_id, id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE core_evidenceblob
ADD CONSTRAINT evidence_blob_repository_tenant_fk
FOREIGN KEY (organization_id, repository_id)
REFERENCES core_repository (organization_id, id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE core_evidenceblob
ADD CONSTRAINT evidence_blob_scope_tenant_fk
FOREIGN KEY (organization_id, access_scope_id)
REFERENCES core_accessscope (organization_id, id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE core_evidenceblob
ADD CONSTRAINT evidence_blob_authorization_tenant_fk
FOREIGN KEY (organization_id, upload_authorization_id)
REFERENCES core_evidenceuploadauthorization (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE core_evidence
ADD CONSTRAINT evidence_artifact_blob_tenant_fk
FOREIGN KEY (organization_id, artifact_blob_id)
REFERENCES core_evidenceblob (organization_id, id) DEFERRABLE INITIALLY DEFERRED;
"""

DROP_SAME_TENANT_SQL = """
ALTER TABLE core_evidence DROP CONSTRAINT IF EXISTS evidence_artifact_blob_tenant_fk;
ALTER TABLE core_evidenceblob
DROP CONSTRAINT IF EXISTS evidence_blob_authorization_tenant_fk;
ALTER TABLE core_evidenceblob DROP CONSTRAINT IF EXISTS evidence_blob_scope_tenant_fk;
ALTER TABLE core_evidenceblob DROP CONSTRAINT IF EXISTS evidence_blob_repository_tenant_fk;
ALTER TABLE core_evidenceuploadauthorization
DROP CONSTRAINT IF EXISTS evidence_upload_scope_tenant_fk;
ALTER TABLE core_evidenceuploadauthorization
DROP CONSTRAINT IF EXISTS evidence_upload_repository_tenant_fk;
"""

LIFECYCLE_SQL = """
CREATE FUNCTION core_validate_evidence_upload_transition() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'evidence upload authorization cannot be deleted'
        USING ERRCODE = '23514';
    END IF;
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.repository_id IS DISTINCT FROM OLD.repository_id
       OR NEW.access_scope_id IS DISTINCT FROM OLD.access_scope_id
       OR NEW.pull_request_number IS DISTINCT FROM OLD.pull_request_number
       OR NEW.commit_sha IS DISTINCT FROM OLD.commit_sha
       OR NEW.filename IS DISTINCT FROM OLD.filename
       OR NEW.declared_sha256 IS DISTINCT FROM OLD.declared_sha256
       OR NEW.declared_size IS DISTINCT FROM OLD.declared_size
       OR NEW.token_hash IS DISTINCT FROM OLD.token_hash
       OR NEW.idempotency_hash IS DISTINCT FROM OLD.idempotency_hash
       OR NEW.request_hash IS DISTINCT FROM OLD.request_hash
       OR NEW.actor_type IS DISTINCT FROM OLD.actor_type
       OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
       OR NEW.credential_id IS DISTINCT FROM OLD.credential_id
       OR NEW.issued_at IS DISTINCT FROM OLD.issued_at
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
        RAISE EXCEPTION 'evidence upload authorization binding is immutable'
        USING ERRCODE = '23514';
    END IF;
    IF NOT (
        (OLD.state = 'ISSUED' AND NEW.state = 'RECEIVING'
         AND NEW.object_key <> ''
         AND NEW.ownership_nonce_hash ~ '^[a-f0-9]{64}$'
         AND NEW.failure_code = ''
         AND NEW.reserved_at IS NOT NULL
         AND NEW.completed_at IS NULL)
        OR (OLD.state = 'ISSUED' AND NEW.state IN ('EXPIRED', 'REVOKED')
            AND NEW.object_key = ''
            AND NEW.ownership_nonce_hash = ''
            AND NEW.failure_code <> ''
            AND NEW.reserved_at IS NULL
            AND NEW.completed_at IS NOT NULL)
        OR (OLD.state = 'RECEIVING' AND NEW.state = 'ACCEPTED'
            AND NEW.object_key IS NOT DISTINCT FROM OLD.object_key
            AND NEW.ownership_nonce_hash IS NOT DISTINCT FROM OLD.ownership_nonce_hash
            AND NEW.reserved_at IS NOT DISTINCT FROM OLD.reserved_at
            AND NEW.failure_code = ''
            AND NEW.completed_at IS NOT NULL)
        OR (OLD.state = 'RECEIVING' AND NEW.state = 'REJECTED'
            AND NEW.object_key IS NOT DISTINCT FROM OLD.object_key
            AND NEW.ownership_nonce_hash IS NOT DISTINCT FROM OLD.ownership_nonce_hash
            AND NEW.reserved_at IS NOT DISTINCT FROM OLD.reserved_at
            AND NEW.failure_code <> ''
            AND NEW.completed_at IS NOT NULL)
    ) THEN
        RAISE EXCEPTION 'invalid evidence upload authorization transition'
        USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER evidence_upload_transition
BEFORE UPDATE OR DELETE ON core_evidenceuploadauthorization
FOR EACH ROW EXECUTE FUNCTION core_validate_evidence_upload_transition();

CREATE FUNCTION core_validate_evidence_blob_change() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'evidence blob cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.repository_id IS DISTINCT FROM OLD.repository_id
       OR NEW.access_scope_id IS DISTINCT FROM OLD.access_scope_id
       OR NEW.upload_authorization_id IS DISTINCT FROM OLD.upload_authorization_id
       OR NEW.object_key IS DISTINCT FROM OLD.object_key
       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
       OR NEW.verified_size IS DISTINCT FROM OLD.verified_size
       OR NEW.detected_media_type IS DISTINCT FROM OLD.detected_media_type
       OR NEW.archive_summary IS DISTINCT FROM OLD.archive_summary
       OR NEW.inspection_version IS DISTINCT FROM OLD.inspection_version
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'evidence blob content identity is immutable'
        USING ERRCODE = '23514';
    END IF;
    IF NOT (
        (OLD.storage_state = 'AVAILABLE' AND NEW.storage_state = 'DELETE_PENDING'
         AND NEW.deletion_reason <> '' AND NEW.storage_error_code = ''
         AND NEW.deleted_at IS NULL)
        OR (OLD.storage_state = 'DELETE_FAILED'
            AND NEW.storage_state = 'DELETE_PENDING'
            AND NEW.deletion_reason <> '' AND NEW.storage_error_code = ''
            AND NEW.deleted_at IS NULL)
        OR (OLD.storage_state = 'DELETE_PENDING' AND NEW.storage_state = 'DELETED'
            AND NEW.deletion_reason IS NOT DISTINCT FROM OLD.deletion_reason
            AND NEW.storage_error_code = '' AND NEW.deleted_at IS NOT NULL)
        OR (OLD.storage_state = 'DELETE_PENDING' AND NEW.storage_state = 'DELETE_FAILED'
            AND NEW.deletion_reason IS NOT DISTINCT FROM OLD.deletion_reason
            AND NEW.storage_error_code <> '' AND NEW.deleted_at IS NULL)
    ) THEN
        RAISE EXCEPTION 'invalid evidence blob storage transition'
        USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER evidence_blob_guard
BEFORE UPDATE OR DELETE ON core_evidenceblob
FOR EACH ROW EXECUTE FUNCTION core_validate_evidence_blob_change();
"""

DROP_LIFECYCLE_SQL = """
DROP TRIGGER IF EXISTS evidence_blob_guard ON core_evidenceblob;
DROP FUNCTION IF EXISTS core_validate_evidence_blob_change();
DROP TRIGGER IF EXISTS evidence_upload_transition ON core_evidenceuploadauthorization;
DROP FUNCTION IF EXISTS core_validate_evidence_upload_transition();
"""

BINDING_SQL = """
CREATE FUNCTION core_validate_evidence_upload_binding() RETURNS trigger AS $$
BEGIN
    IF TG_TABLE_NAME = 'core_evidenceblob' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM core_evidenceuploadauthorization upload_auth
            WHERE upload_auth.id = NEW.upload_authorization_id
              AND upload_auth.organization_id = NEW.organization_id
              AND upload_auth.repository_id = NEW.repository_id
              AND upload_auth.access_scope_id = NEW.access_scope_id
              AND upload_auth.state = 'ACCEPTED'
              AND upload_auth.object_key = NEW.object_key
              AND upload_auth.declared_sha256 = NEW.content_hash
              AND upload_auth.declared_size = NEW.verified_size
        ) THEN
            RAISE EXCEPTION 'evidence blob authorization binding is invalid'
            USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'core_evidence' AND NEW.artifact_blob_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM core_evidenceblob blob
            JOIN core_evidenceuploadauthorization upload_auth
              ON upload_auth.id = blob.upload_authorization_id
             AND upload_auth.organization_id = blob.organization_id
            JOIN core_evidencemanifest manifest
              ON manifest.id = NEW.manifest_id
             AND manifest.organization_id = NEW.organization_id
            WHERE blob.id = NEW.artifact_blob_id
              AND blob.organization_id = NEW.organization_id
              AND blob.repository_id = manifest.repository_id
              AND blob.access_scope_id = manifest.access_scope_id
              AND blob.storage_state = 'AVAILABLE'
              AND blob.content_hash = NEW.content_hash
              AND upload_auth.state = 'ACCEPTED'
              AND upload_auth.pull_request_number = manifest.pull_request_number
              AND upload_auth.commit_sha = NEW.commit_sha
        ) THEN
            RAISE EXCEPTION 'evidence artifact blob binding is invalid'
            USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER evidence_blob_authorization_binding
AFTER INSERT ON core_evidenceblob DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_evidence_upload_binding();
CREATE CONSTRAINT TRIGGER evidence_artifact_blob_binding
AFTER INSERT ON core_evidence DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION core_validate_evidence_upload_binding();
"""

DROP_BINDING_SQL = """
DROP TRIGGER IF EXISTS evidence_artifact_blob_binding ON core_evidence;
DROP TRIGGER IF EXISTS evidence_blob_authorization_binding ON core_evidenceblob;
DROP FUNCTION IF EXISTS core_validate_evidence_upload_binding();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0020_ratelimitbucket_retentionrun_and_more"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.CreateModel(
            name="EvidenceUploadAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pull_request_number", models.PositiveIntegerField()),
                ("commit_sha", models.CharField(max_length=40)),
                ("filename", models.CharField(max_length=128)),
                ("declared_sha256", models.CharField(max_length=64)),
                ("declared_size", models.PositiveIntegerField()),
                ("token_hash", models.CharField(editable=False, max_length=64)),
                ("idempotency_hash", models.CharField(editable=False, max_length=64)),
                ("request_hash", models.CharField(editable=False, max_length=64)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=200)),
                ("credential_id", models.UUIDField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("RECEIVING", "Receiving"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ISSUED",
                        max_length=16,
                    ),
                ),
                ("object_key", models.CharField(blank=True, editable=False, max_length=200)),
                (
                    "ownership_nonce_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.accessscope",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_key", models.CharField(editable=False, max_length=200, unique=True)),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("verified_size", models.PositiveIntegerField(editable=False)),
                (
                    "detected_media_type",
                    models.CharField(
                        choices=[
                            ("application/json", "Json"),
                            ("application/zip", "Zip"),
                            ("application/x-tar", "Tar"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("archive_summary", models.JSONField(default=dict, editable=False)),
                ("inspection_version", models.CharField(editable=False, max_length=64)),
                (
                    "storage_state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DELETE_PENDING", "Delete Pending"),
                            ("DELETE_FAILED", "Delete Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("deletion_reason", models.CharField(blank=True, max_length=100)),
                ("storage_error_code", models.CharField(blank=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.accessscope",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.repository",
                    ),
                ),
                (
                    "upload_authorization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.evidenceuploadauthorization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidence",
            name="artifact_blob",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.evidenceblob",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceuploadauthorization",
            index=models.Index(
                condition=Q(state="ISSUED"),
                fields=["expires_at", "id"],
                name="core_ev_upload_expiry_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceuploadauthorization",
            index=models.Index(
                fields=["organization", "repository", "pull_request_number", "commit_sha"],
                name="core_ev_upload_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceblob",
            index=models.Index(
                fields=["organization", "storage_state", "created_at", "id"],
                name="core_ev_blob_storage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceblob",
            index=models.Index(
                fields=["organization", "repository", "content_hash"],
                name="core_ev_blob_digest_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="core_evidence_upload_org_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "id"),
                name="core_evidence_upload_org_repo_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.UniqueConstraint(
                fields=("token_hash",),
                name="core_evidence_upload_token_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "idempotency_hash"),
                name="core_evidence_upload_idem_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(commit_sha__regex=r"^[a-f0-9]{40}$"),
                name="core_evidence_upload_commit_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(declared_sha256__regex=r"^[a-f0-9]{64}$"),
                name="core_evidence_upload_declared_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(token_hash__regex=r"^[a-f0-9]{64}$"),  # noqa: S106
                name="core_evidence_upload_token_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(idempotency_hash__regex=r"^[a-f0-9]{64}$"),
                name="core_evidence_upload_idem_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(request_hash__regex=r"^[a-f0-9]{64}$"),
                name="core_evidence_upload_request_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(ownership_nonce_hash="")
                | Q(ownership_nonce_hash__regex=r"^[a-f0-9]{64}$"),
                name="core_ev_upload_owner_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(pull_request_number__gte=1),
                name="core_evidence_upload_pr_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(declared_size__gte=1, declared_size__lte=4_096),
                name="core_evidence_upload_size_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=Q(expires_at__gt=F("issued_at")),
                name="core_evidence_upload_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        state="ISSUED",
                        object_key="",
                        ownership_nonce_hash="",
                        failure_code="",
                        reserved_at__isnull=True,
                        completed_at__isnull=True,
                    )
                    | Q(
                        state="RECEIVING",
                        ownership_nonce_hash__regex=r"^[a-f0-9]{64}$",
                        failure_code="",
                        reserved_at__isnull=False,
                        completed_at__isnull=True,
                    )
                    | Q(
                        state="ACCEPTED",
                        ownership_nonce_hash__regex=r"^[a-f0-9]{64}$",
                        failure_code="",
                        reserved_at__isnull=False,
                        completed_at__isnull=False,
                    )
                    | (
                        Q(
                            state="REJECTED",
                            ownership_nonce_hash__regex=r"^[a-f0-9]{64}$",
                            reserved_at__isnull=False,
                            completed_at__isnull=False,
                        )
                        & ~Q(failure_code="")
                    )
                    | (
                        Q(
                            state__in=["EXPIRED", "REVOKED"],
                            object_key="",
                            ownership_nonce_hash="",
                            reserved_at__isnull=True,
                            completed_at__isnull=False,
                        )
                        & ~Q(failure_code="")
                    )
                ),
                name="core_evidence_upload_state_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceuploadauthorization",
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        state__in=["ISSUED", "EXPIRED", "REVOKED"],
                        object_key="",
                        ownership_nonce_hash="",
                    )
                    | (Q(state__in=["RECEIVING", "ACCEPTED", "REJECTED"]) & ~Q(object_key=""))
                ),
                name="core_evidence_upload_object_key_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceblob",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="core_evidence_blob_org_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceblob",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "id"),
                name="core_evidence_blob_org_repo_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceblob",
            constraint=models.CheckConstraint(
                condition=Q(content_hash__regex=r"^[a-f0-9]{64}$"),
                name="core_evidence_blob_content_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceblob",
            constraint=models.CheckConstraint(
                condition=Q(verified_size__gte=1, verified_size__lte=4_096),
                name="core_evidence_blob_size_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceblob",
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        storage_state="AVAILABLE",
                        deletion_reason="",
                        storage_error_code="",
                        deleted_at__isnull=True,
                    )
                    | Q(
                        storage_state="DELETE_PENDING",
                        storage_error_code="",
                        deleted_at__isnull=True,
                    )
                    | (
                        Q(storage_state="DELETE_FAILED", deleted_at__isnull=True)
                        & ~Q(deletion_reason="")
                        & ~Q(storage_error_code="")
                    )
                    | (
                        Q(
                            storage_state="DELETED",
                            storage_error_code="",
                            deleted_at__isnull=False,
                        )
                        & ~Q(deletion_reason="")
                    )
                ),
                name="core_evidence_blob_storage_coherent",
            ),
        ),
        migrations.RunSQL(sql=SAME_TENANT_SQL, reverse_sql=DROP_SAME_TENANT_SQL),
        migrations.RunSQL(sql=LIFECYCLE_SQL, reverse_sql=DROP_LIFECYCLE_SQL),
        migrations.RunSQL(sql=BINDING_SQL, reverse_sql=DROP_BINDING_SQL),
    ]
