# Generated by Django 5.2.13 on 2026-08-08 18:33

from typing import ClassVar

from django.db import migrations, models


def backfill_legacy_evaluator_task_identity(apps, schema_editor) -> None:
    evaluator_task = apps.get_model("core", "EvaluatorTask")
    evaluator_task.objects.filter(attempt_count__gt=0).update(
        claimed_by_actor_type="LEGACY",
        claimed_by_actor_id="legacy-unverifiable",
    )


IDENTITY_GUARDS_SQL = """
CREATE FUNCTION core_guard_assurance_initiator_identity() RETURNS trigger AS $$
BEGIN
    IF NEW.initiated_by_actor_type IS DISTINCT FROM OLD.initiated_by_actor_type
       OR NEW.initiated_by_actor_id IS DISTINCT FROM OLD.initiated_by_actor_id
       OR NEW.initiated_by_credential_id IS DISTINCT FROM OLD.initiated_by_credential_id
    THEN
        RAISE EXCEPTION 'assurance run initiator identity is immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assurancerun_initiator_identity_immutable
BEFORE UPDATE OF initiated_by_actor_type, initiated_by_actor_id, initiated_by_credential_id
ON core_assurancerun
FOR EACH ROW EXECUTE FUNCTION core_guard_assurance_initiator_identity();

CREATE FUNCTION core_guard_evaluator_claim_identity() RETURNS trigger AS $$
BEGIN
    IF NEW.claimed_by_actor_type IS DISTINCT FROM OLD.claimed_by_actor_type
       OR NEW.claimed_by_actor_id IS DISTINCT FROM OLD.claimed_by_actor_id
       OR NEW.claimed_by_credential_id IS DISTINCT FROM OLD.claimed_by_credential_id
    THEN
        IF NOT (
            OLD.state = 'PENDING'
            AND OLD.attempt_count = 0
            AND OLD.claimed_by_actor_type = ''
            AND OLD.claimed_by_actor_id = ''
            AND OLD.claimed_by_credential_id IS NULL
            AND NEW.state = 'CLAIMED'
            AND NEW.attempt_count = 1
        ) AND NOT (
            OLD.state = 'CLAIMED'
            AND NEW.state = 'CLAIMED'
            AND OLD.lease_expires_at <= CURRENT_TIMESTAMP
            AND NEW.attempt_count = OLD.attempt_count + 1
        ) THEN
            RAISE EXCEPTION 'evaluator claim identity cannot be switched'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER evaluatortask_claim_identity_guard
BEFORE UPDATE OF claimed_by_actor_type, claimed_by_actor_id, claimed_by_credential_id
ON core_evaluatortask
FOR EACH ROW EXECUTE FUNCTION core_guard_evaluator_claim_identity();

CREATE FUNCTION core_validate_evaluator_attempt_identity() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM core_evaluatortask task
        WHERE task.id = NEW.evaluator_task_id
          AND task.organization_id = NEW.organization_id
          AND task.claimed_by_actor_type = NEW.claimed_by_actor_type
          AND task.claimed_by_actor_id = NEW.claimed_by_actor_id
          AND task.claimed_by_credential_id IS NOT DISTINCT FROM NEW.claimed_by_credential_id
    ) THEN
        RAISE EXCEPTION 'evaluator attempt identity must match its current claim'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER evaluatorattempt_claim_identity_guard
BEFORE INSERT ON core_evaluatorattempt
FOR EACH ROW EXECUTE FUNCTION core_validate_evaluator_attempt_identity();
"""

DROP_IDENTITY_GUARDS_SQL = """
DROP TRIGGER IF EXISTS evaluatorattempt_claim_identity_guard ON core_evaluatorattempt;
DROP FUNCTION IF EXISTS core_validate_evaluator_attempt_identity();
DROP TRIGGER IF EXISTS evaluatortask_claim_identity_guard ON core_evaluatortask;
DROP FUNCTION IF EXISTS core_guard_evaluator_claim_identity();
DROP TRIGGER IF EXISTS assurancerun_initiator_identity_immutable ON core_assurancerun;
DROP FUNCTION IF EXISTS core_guard_assurance_initiator_identity();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0021_evidence_upload_authorization_and_blob"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="auditevent",
            name="credential_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="initiated_by_actor_id",
            field=models.CharField(default="legacy-unverifiable", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="initiated_by_actor_type",
            field=models.CharField(default="SYSTEM", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assurancerun",
            name="initiated_by_credential_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="claimed_by_actor_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="claimed_by_actor_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="claimed_by_credential_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_legacy_evaluator_task_identity,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="evaluatorattempt",
            name="claimed_by_actor_id",
            field=models.CharField(default="legacy-unverifiable", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluatorattempt",
            name="claimed_by_actor_type",
            field=models.CharField(default="LEGACY", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluatorattempt",
            name="claimed_by_credential_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="assurancerun",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(initiated_by_actor_type="") & ~models.Q(initiated_by_actor_id="")
                ),
                name="core_assurance_initiator_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        claimed_by_actor_type="",
                        claimed_by_actor_id="",
                        claimed_by_credential_id__isnull=True,
                    )
                    | (~models.Q(claimed_by_actor_type="") & ~models.Q(claimed_by_actor_id=""))
                ),
                name="core_evaluator_claim_identity_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatorattempt",
            constraint=models.CheckConstraint(
                condition=(~models.Q(claimed_by_actor_type="") & ~models.Q(claimed_by_actor_id="")),
                name="core_evaluator_attempt_identity_present",
            ),
        ),
        migrations.RunSQL(
            sql=IDENTITY_GUARDS_SQL,
            reverse_sql=DROP_IDENTITY_GUARDS_SQL,
        ),
    ]
