# Generated by Django 5.2.13 on 2026-08-09

import uuid
from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [("core", "0022_independent_evaluator_identity")]

    operations: ClassVar = [
        migrations.AddField(
            model_name="evaluatortask",
            name="claim_idempotency_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("claim_idempotency_sha256", "")),
                fields=("organization", "claim_idempotency_sha256"),
                name="core_evaluator_claim_idem_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("claim_idempotency_sha256", ""))
                    | models.Q(("claim_idempotency_sha256__regex", "^[a-f0-9]{64}$"))
                ),
                name="core_evaluator_claim_idem_sha",
            ),
        ),
        migrations.CreateModel(
            name="BootstrapRecovery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_sha256", models.CharField(max_length=64, unique=True)),
                ("idempotency_sha256", models.CharField(max_length=64, unique=True)),
                ("recovery_count", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.accessscope",
                    ),
                ),
                (
                    "issued_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiator_bootstrap_recoveries",
                        to="core.repositoryaccesstoken",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.membership",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.repository",
                    ),
                ),
                (
                    "reviewer_issued_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewer_bootstrap_recoveries",
                        to="core.repositoryaccesstoken",
                    ),
                ),
                (
                    "reviewer_service_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewer_bootstrap_recoveries",
                        to="core.serviceidentity",
                    ),
                ),
                (
                    "service_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bootstrap_recoveries",
                        to="core.serviceidentity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bootstraprecovery",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_sha256__regex", "^[a-f0-9]{64}$")),
                name="core_bootstrap_request_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="bootstraprecovery",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_sha256__regex", "^[a-f0-9]{64}$")),
                name="core_bootstrap_idem_sha",
            ),
        ),
    ]
