# Generated by Django 5.2.13 on 2026-08-10

from __future__ import annotations

import hashlib
import json
from typing import ClassVar

from django.db import migrations, models

PRE_SELECTOR_BINDING_UNKNOWN_SHA256 = hashlib.sha256(
    json.dumps(
        {"mode": "PRE_SELECTOR_BINDING_UNKNOWN"},
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
        allow_nan=False,
    ).encode()
).hexdigest()


def bind_existing_claims(apps: object, _schema_editor: object) -> None:
    evaluator_task = apps.get_model("core", "EvaluatorTask")  # type: ignore[attr-defined]
    evaluator_task.objects.exclude(claim_idempotency_sha256="").filter(
        claim_selector_sha256=""
    ).update(claim_selector_sha256=PRE_SELECTOR_BINDING_UNKNOWN_SHA256)


def unbind_existing_claims(apps: object, _schema_editor: object) -> None:
    evaluator_task = apps.get_model("core", "EvaluatorTask")  # type: ignore[attr-defined]
    evaluator_task.objects.update(claim_selector_sha256="")


class Migration(migrations.Migration):
    dependencies: ClassVar = [("core", "0023_acceptance_recovery")]

    operations: ClassVar = [
        migrations.AddField(
            model_name="evaluatortask",
            name="claim_selector_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(bind_existing_claims, unbind_existing_claims),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(claim_idempotency_sha256="", claim_selector_sha256="")
                    | (
                        ~models.Q(claim_idempotency_sha256="")
                        & models.Q(claim_selector_sha256__regex="^[a-f0-9]{64}$")
                    )
                ),
                name="core_evaluator_claim_selector_sha",
            ),
        ),
    ]
