# Generated by Django 5.2.13 on 2026-08-22

from __future__ import annotations

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models

CLAIM_IDENTITY_GUARD_CLOCK_SQL = """
CREATE OR REPLACE FUNCTION core_guard_evaluator_claim_identity() RETURNS trigger AS $$
BEGIN
    IF NEW.claimed_by_actor_type IS DISTINCT FROM OLD.claimed_by_actor_type
       OR NEW.claimed_by_actor_id IS DISTINCT FROM OLD.claimed_by_actor_id
       OR NEW.claimed_by_credential_id IS DISTINCT FROM OLD.claimed_by_credential_id
    THEN
        IF NOT (
            OLD.state = 'PENDING'
            AND OLD.attempt_count = 0
            AND OLD.claimed_by_actor_type = ''
            AND OLD.claimed_by_actor_id = ''
            AND OLD.claimed_by_credential_id IS NULL
            AND NEW.state = 'CLAIMED'
            AND NEW.attempt_count = 1
        ) AND NOT (
            OLD.state = 'CLAIMED'
            AND NEW.state = 'CLAIMED'
            AND OLD.lease_expires_at <= clock_timestamp()
            AND NEW.attempt_count = OLD.attempt_count + 1
        ) THEN
            RAISE EXCEPTION 'evaluator claim identity cannot be switched'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


CLAIM_IDENTITY_GUARD_TRANSACTION_SQL = CLAIM_IDENTITY_GUARD_CLOCK_SQL.replace(
    "OLD.lease_expires_at <= clock_timestamp()",
    "OLD.lease_expires_at <= CURRENT_TIMESTAMP",
)

REVIEWER_BINDING_GUARD_SQL = """
CREATE FUNCTION core_validate_evaluator_reviewer_binding() RETURNS trigger AS $$
BEGIN
    IF NEW.reviewer_service_identity_id IS NULL
       AND NEW.reviewer_token_id IS NULL
    THEN
        RETURN NEW;
    END IF;

    IF NEW.reviewer_service_identity_id IS NULL
       OR NEW.reviewer_token_id IS NULL
       OR NOT EXISTS (
           SELECT 1
           FROM core_repositoryaccesstoken token
           JOIN core_bootstraprecovery recovery
             ON recovery.organization_id = NEW.organization_id
            AND recovery.repository_id = NEW.repository_id
            AND recovery.reviewer_service_identity_id = NEW.reviewer_service_identity_id
            AND recovery.reviewer_issued_token_id = NEW.reviewer_token_id
           JOIN core_assurancerun assurance_run
             ON assurance_run.id = NEW.assurance_run_id
            AND assurance_run.organization_id = NEW.organization_id
            AND assurance_run.repository_id = NEW.repository_id
            AND assurance_run.initiated_by_actor_type = 'SERVICE'
            AND assurance_run.initiated_by_actor_id = recovery.service_identity_id::text
           WHERE token.id = NEW.reviewer_token_id
             AND token.organization_id = NEW.organization_id
             AND token.repository_id = NEW.repository_id
             AND token.service_identity_id = NEW.reviewer_service_identity_id
       )
    THEN
        RAISE EXCEPTION 'evaluator reviewer binding is not the current bootstrap reviewer'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF NEW.reviewer_service_identity_id IS DISTINCT FROM OLD.reviewer_service_identity_id
        THEN
            RAISE EXCEPTION 'evaluator reviewer service identity is immutable'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.reviewer_token_id IS DISTINCT FROM OLD.reviewer_token_id
           AND NOT (
               OLD.reviewer_token_id IS NOT NULL
               AND OLD.state IN ('PENDING', 'CLAIMED')
               AND EXISTS (
                   SELECT 1
                   FROM core_repositoryaccesstoken old_token
                   WHERE old_token.id = OLD.reviewer_token_id
                     AND old_token.revoked_at IS NOT NULL
                     AND old_token.service_identity_id = NEW.reviewer_service_identity_id
               )
               AND (
                   OLD.state = 'PENDING'
                   OR NEW.lease_expires_at <= clock_timestamp()
               )
           )
        THEN
            RAISE EXCEPTION 'evaluator reviewer credential binding is immutable'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER evaluatortask_reviewer_binding_guard
BEFORE INSERT OR UPDATE OF reviewer_service_identity_id, reviewer_token_id
ON core_evaluatortask
FOR EACH ROW EXECUTE FUNCTION core_validate_evaluator_reviewer_binding();
"""


DROP_REVIEWER_BINDING_GUARD_SQL = """
DROP TRIGGER IF EXISTS evaluatortask_reviewer_binding_guard ON core_evaluatortask;
DROP FUNCTION IF EXISTS core_validate_evaluator_reviewer_binding();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar = [("core", "0024_evaluator_claim_selector")]

    operations: ClassVar = [
        migrations.AddField(
            model_name="evaluatortask",
            name="reviewer_service_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bound_evaluator_tasks",
                to="core.serviceidentity",
            ),
        ),
        migrations.AddField(
            model_name="evaluatortask",
            name="reviewer_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bound_evaluator_tasks",
                to="core.repositoryaccesstoken",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluatortask",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        reviewer_service_identity__isnull=True,
                        reviewer_token__isnull=True,
                    )
                    | models.Q(
                        reviewer_service_identity__isnull=False,
                        reviewer_token__isnull=False,
                    )
                ),
                name="core_evaluator_reviewer_binding_pair",
            ),
        ),
        migrations.RunSQL(
            sql=CLAIM_IDENTITY_GUARD_CLOCK_SQL,
            reverse_sql=CLAIM_IDENTITY_GUARD_TRANSACTION_SQL,
        ),
        migrations.RunSQL(
            sql=REVIEWER_BINDING_GUARD_SQL,
            reverse_sql=DROP_REVIEWER_BINDING_GUARD_SQL,
        ),
    ]
